### ISSUE TITLE
Quickbuild sometimes just stops working. Even for other players

### ISSUE THREAD

**Issue by HorizonFade** [DarkflameUniverse/DarkflameServer#122] opened 2021-12-08 06:26 UTC
![image](https://user-images.githubusercontent.com/16822185/145159234-a7068535-c65b-41f6-9b7b-814b6ec1ec76.png)

**Comment by BustosAndrew** [comment] 2021-12-08 06:59
Go back to your list of minifigures and load back in. Usually fixes quick build.

**Comment by IAmVolvic** [comment] 2021-12-08 07:12
> Go back to your list of minifigures and load back in. Usually fixes quick build.

That's true but not always, i've had users try this to no effect.

**Comment by averysumner** [comment] 2021-12-08 07:46
Likely a serialization issue, able to reproduce.

**Comment by HorizonFade** [comment] 2021-12-09 16:00
i see its ultra annoying as an Engineer not being able to build turrets

**Comment by HorizonFade** [comment] 2021-12-09 16:00
hope its getting fixed soon

**Comment by IAmVolvic** [comment] 2021-12-10 22:30
Users are experiencing this problem all over the place where trying to quick build works then randomly just stops. I have around 10 people at AG just standing there waiting for the red button quick to work again.

**Comment by MickVermeulen** [comment] 2021-12-12 08:55
Bumping prio as I'm getting quite a lot of reports of this hindering gameplay experience.

**Comment by Jettford** [comment] 2021-12-13 01:08
Is this the same bug that happened in live?

Where the quickbuilds just broke for some reason so a server engineer added a trigger that would fix it if you stood near it for a little bit?

**Comment by Terrev** [comment] 2021-12-14 18:02
> Is this the same bug that happened in live?
> 
> Where the quickbuilds just broke for some reason so a server engineer added a trigger that would fix it if you stood near it for a little bit?

you thinking of this? that's a different issue http://nic-gamedev.blogspot.com/2013/02/the-bounce-pad-hack-in-lego-universe.html

**Comment by Jettford** [comment] 2021-12-14 22:03
Ah yeah that was it, I couldn't exactly remember what the issue was there, never mind.

**Comment by MickVermeulen** [comment] 2021-12-15 09:18
So apparently this is fixed by just serializing the entity again. According to Wincent, simply calling /inspect 2 -s near the object as a GM will fix the issue for people. Of course a bodge way to do this is just periodically serialize entities with a RebuildComponent. We do need to look into what exactly causes this, though. Although, given that this was even experienced in live, I think it’ll be hard to pin down.

**Comment by sersorrel** [comment] 2021-12-18 01:46
Is there any particular reason to pass `-s` to /inspect? It looks like the entity will get serialised even if you just `/inspect 2`. (sidenote: why 2, and not e.g. 12 for a RebuildComponent? I'd check if the latter actually works, but I don't have a good way to reproduce the problem.)

**Comment by MickVermeulen** [comment] 2021-12-19 10:54
> Is there any particular reason to pass `-s` to /inspect? It looks like the entity will get serialised even if you just `/inspect 2`. (sidenote: why 2, and not e.g. ~12~ 48 for a RebuildComponent? I'd check if the latter actually works, but I don't have a good way to reproduce the problem.)

Passing, 2 or -s doesn't really matter. It's just one that's very standard as it contains all the config options for the entity. /inspect serialises it either way. So any of the inspect commands should resolve the issue temporarily.

**Comment by soir20** [comment] 2022-01-21 23:48
I've been playing an engineer character, so I've been able to observe this issue a lot with turret builds. What I've noticed is that it seems to happen when your character is moving at the same time you press "shift" to start a build. Sometimes, I'm not pressing any buttons, but the terrain is uneven, so my character moves ever-so-slightly just as I press "shift." If I am absolutely still, the builds tend to work. My experience is similar to the description in #206 (duplicate).

It happens particularly often when trying to build the bounce pad to the Pirate Camp in Gnarled Forest because I'm trying to dodge the ape. It also frequently happens at the end of the path with the maelstrom horsemen leading to the Forbidden Valley dragon battle, as my character seems to slide a tiny bit on uneven parts of the terrain. I can consistently prevent the problem by deploying the turret build on flatter terrain where I do not move (in the same area).

**Comment by Xiphoseer** [comment] 2022-02-05 15:38
> What I've noticed is that it seems to happen when your character is moving at the same time you press "shift" to start a build.

Yeah, the few times I've had this bug it also seemed like something that was triggered like:
- Shift icon is visible
- User presses shift
- Moves away (?)
- QuickBuild doesn't happen (out of range race-condition)?
- State doesn't reset so it's stuck

**Comment by EmosewaMC** [comment] 2022-04-20 03:44
I have figured out a 100% consistent reproduction of the issue.  Working on a fix.

**Comment by EmosewaMC** [comment] 2022-04-26 22:48
So what we are working with here is two reproductions of potentially the same issue, one happens commonly in Avant Gardens and the other happens commonly with Engineer Quickbuild spawns.  Still investigating the fix.  Not an easy one.

**Closed** 2022-06-16 16:06 UTC
Labels: bug, P-high, A-game
