### ISSUE TITLE
CppScript returned InvalidScript

### ISSUE THREAD

**Issue by Capital-EX** [DarkflameUniverse/DarkflameServer#23] opened 2021-12-06 02:11 UTC
When attempting to start the server, the script loader tries to load `scripts\ai\AG\L_AG_SHIP_SHAKE.lua` which causes the server to throw an `InvalidScript` error. I'm not sure if this is an issue from Unix using `/` and not `\` to denote file paths. All, parts of the path are correctly named. I have attempted this with both `build/res/scripts` and `build/scripts`.

**Comment by j-usti-n** [comment] 2021-12-06 02:13
I had this issue as well, are you running a windows native build by chance?

**Comment by j-usti-n** [comment] 2021-12-06 02:13
I think the path issue might be correct, because I cannot load navmesh on native windows build as well

**Comment by Capital-EX** [comment] 2021-12-06 02:19
I'm running it on Manjaro Linux. However, if you are having the same issue than something else must be up.

**Comment by Jettford** [comment] 2021-12-06 02:49
This is fine, not actually an issue.

**Comment by Jettford** [comment] 2021-12-06 02:50
also duplicate of #9

**Comment by Wincent01** [comment] 2021-12-06 07:58
That particular script is unused, this notice by the server may be ignored. Note that the server does not load LUA scripts, it uses C++ translations of those LUA scripts found in `dScripts`. Closing.

**Closed by Wincent01** 2021-12-06 07:58 UTC
