### ISSUE TITLE
BUG: Massive lag only on the server-side after the tutorial

### ISSUE THREAD

**Issue by Paulinhoice** [DarkflameUniverse/DarkflameServer#1624] opened 2024-07-07 03:15 UTC
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

c3f6ef5a

### Issue Description

Hello, I followed the tutorial provided in the repository and was able to connect to the server normally. I followed the tutorial without any issues, but as soon as I talk to the first NPC in the first world, the server experiences huge delays. I kill the enemies, and 5 seconds later, they come back (they don't respawn, but rather, it's as if I never killed them). In the mission to get the initial items (sword, spear, axe?), I try to interact with the NPC, and it takes a long time for him to respond.

Here is the log of the console:
```
Jul 07 02:55:27 ip-172-31-5-62 MasterServer[14132]: [07-07-24 02:55:25 UserManager.cpp:522] Transferring GenuineUsefulNonsense to Zone 1100 (Instance 3 | Clone 0 | Mythran Shift: false) wi>
Jul 07 02:55:27 ip-172-31-5-62 MasterServer[14132]: [07-07-24 02:55:25 UserManager.cpp:148] Deleted user 1
Jul 07 02:55:30 ip-172-31-5-62 MasterServer[18341]: [07-07-24 02:55:20 WorldServer.cpp:768] Got new session alert for user paulinhoice
Jul 07 02:55:30 ip-172-31-5-62 MasterServer[18341]: [07-07-24 02:55:20 WorldServer.cpp:772] But they're not logged in?
Jul 07 02:55:31 ip-172-31-5-62 MasterServer[18353]: [07-07-24 02:55:20 WorldServer.cpp:768] Got new session alert for user paulinhoice
Jul 07 02:55:31 ip-172-31-5-62 MasterServer[18353]: [07-07-24 02:55:20 WorldServer.cpp:772] But they're not logged in?
Jul 07 02:55:31 ip-172-31-5-62 MasterServer[18353]: [07-07-24 02:55:25 WorldServer.cpp:745] Got affirmation request of transfer 2
Jul 07 02:55:31 ip-172-31-5-62 MasterServer[18353]: [07-07-24 02:55:26 WorldServer.cpp:699] User paulinhoice authenticated with correct key.
Jul 07 02:55:31 ip-172-31-5-62 MasterServer[18353]: [07-07-24 02:55:26 Character.cpp:77] Loaded xmlData for character GenuineUsefulNonsense (2)!
Jul 07 02:55:31 ip-172-31-5-62 MasterServer[18353]: [07-07-24 02:55:26 User.cpp:42] Loaded 2 as it is the last used char
Jul 07 02:55:32 ip-172-31-5-62 MasterServer[14130]: [07-07-24 02:55:25 PlayerContainer.cpp:68] Failed to find user: 0
Jul 07 02:55:32 ip-172-31-5-62 MasterServer[14130]: [07-07-24 02:55:25 PlayerContainer.cpp:68] Failed to find user: 0
Jul 07 02:55:32 ip-172-31-5-62 MasterServer[14136]: [07-07-24 02:55:20 AuthPackets.cpp:305] Set sessionKey: 384185191 for user paulinhoice
Jul 07 02:55:35 ip-172-31-5-62 MasterServer[14123]: [07-07-24 02:55:20 MasterServer.cpp:490] Received zone transfer req
Jul 07 02:55:35 ip-172-31-5-62 MasterServer[14123]: [07-07-24 02:55:20 InstanceManager.cpp:33] Searching for an instance for mapID 0/0
Jul 07 02:55:35 ip-172-31-5-62 MasterServer[14123]: [07-07-24 02:55:20 MasterServer.cpp:509] Instance: 0/0/0 -> 1
Jul 07 02:55:35 ip-172-31-5-62 MasterServer[14123]: [07-07-24 02:55:20 MasterServer.cpp:509] Instance: 1000/0/2 -> 0
Jul 07 02:55:35 ip-172-31-5-62 MasterServer[14123]: [07-07-24 02:55:20 MasterServer.cpp:509] Instance: 1100/0/3 -> 0
Jul 07 02:55:35 ip-172-31-5-62 MasterServer[14123]: [07-07-24 02:55:20 MasterServer.cpp:520] Responding to transfer request 2 for zone 0 0
Jul 07 02:55:35 ip-172-31-5-62 MasterServer[14123]: [07-07-24 02:55:20 InstanceManager.cpp:186] Sent affirmation request 2 to 0/0
Jul 07 02:55:35 ip-172-31-5-62 MasterServer[14123]: [07-07-24 02:55:20 MasterServer.cpp:775] Got affirmation of transfer 2
Jul 07 02:55:35 ip-172-31-5-62 MasterServer[14123]: [07-07-24 02:55:20 MasterServer.cpp:783] Affirmation complete 2
Jul 07 02:55:35 ip-172-31-5-62 MasterServer[14123]: [07-07-24 02:55:20 MasterServer.cpp:608] Got sessionKey 384185191 for user paulinhoice
Jul 07 02:55:35 ip-172-31-5-62 MasterServer[14123]: [07-07-24 02:55:21 MasterServer.cpp:616] Requesting session key for paulinhoice
Jul 07 02:55:35 ip-172-31-5-62 MasterServer[14123]: [07-07-24 02:55:25 MasterServer.cpp:490] Received zone transfer req
Jul 07 02:55:35 ip-172-31-5-62 MasterServer[14123]: [07-07-24 02:55:25 InstanceManager.cpp:33] Searching for an instance for mapID 1100/0
Jul 07 02:55:35 ip-172-31-5-62 MasterServer[14123]: [07-07-24 02:55:25 MasterServer.cpp:509] Instance: 0/0/0 -> 0
Jul 07 02:55:35 ip-172-31-5-62 MasterServer[14123]: [07-07-24 02:55:25 MasterServer.cpp:509] Instance: 1000/0/2 -> 0
Jul 07 02:55:35 ip-172-31-5-62 MasterServer[14123]: [07-07-24 02:55:25 MasterServer.cpp:509] Instance: 1100/0/3 -> 1
Jul 07 02:55:35 ip-172-31-5-62 MasterServer[14123]: [07-07-24 02:55:25 MasterServer.cpp:520] Responding to transfer request 2 for zone 1100 0
Jul 07 02:55:35 ip-172-31-5-62 MasterServer[14123]: [07-07-24 02:55:25 InstanceManager.cpp:186] Sent affirmation request 2 to 1100/0
Jul 07 02:55:35 ip-172-31-5-62 MasterServer[14123]: [07-07-24 02:55:25 MasterServer.cpp:775] Got affirmation of transfer 2
Jul 07 02:55:35 ip-172-31-5-62 MasterServer[14123]: [07-07-24 02:55:25 MasterServer.cpp:783] Affirmation complete 2
Jul 07 02:55:35 ip-172-31-5-62 MasterServer[14123]: [07-07-24 02:55:26 MasterServer.cpp:616] Requesting session key for paulinhoice
Jul 07 02:55:45 ip-172-31-5-62 MasterServer[18353]: [07-07-24 02:55:35 WorldServer.cpp:1014] Received level load complete from user.
Jul 07 02:55:45 ip-172-31-5-62 MasterServer[18353]: [07-07-24 02:55:35 ControllablePhysicsComponent.cpp:52] Using patch to load minifig physics
Jul 07 02:55:45 ip-172-31-5-62 MasterServer[18353]: [07-07-24 02:55:35 WorldPackets.cpp:134] Sent CreateCharacter for ID: 1152921508901814274
Jul 07 02:56:00 ip-172-31-5-62 MasterServer[18353]: [07-07-24 02:55:52 GameMessageHandler.cpp:170] Player GenuineUsefulNonsense (1152921508901814274) loaded.
Jul 07 02:56:01 ip-172-31-5-62 MasterServer[14130]: [07-07-24 02:55:35 PlayerContainer.cpp:54] Added user: GenuineUsefulNonsense (1152921508901814274), zone: 1100
Jul 07 02:57:30 ip-172-31-5-62 MasterServer[18353]: [07-07-24 02:57:19 SkillComponent.cpp:58] Failed to find skill with uid (19)!
Jul 07 02:57:30 ip-172-31-5-62 MasterServer[18353]: [07-07-24 02:57:20 SkillComponent.cpp:58] Failed to find skill with uid (23)!
Jul 07 02:57:45 ip-172-31-5-62 MasterServer[18353]: [07-07-24 02:57:42 CharacterComponent.cpp:378] Time since last save: 127
Jul 07 02:57:45 ip-172-31-5-62 MasterServer[18353]: [07-07-24 02:57:42 Character.cpp:314] 2:GenuineUsefulNonsense Saved character to Database in: 0.004445s
Jul 07 02:57:45 ip-172-31-5-62 MasterServer[18353]: [07-07-24 02:57:42 WorldServer.cpp:816] Deleting player 1152921508901814274
Jul 07 02:57:45 ip-172-31-5-62 MasterServer[18353]: [07-07-24 02:57:42 Entity.cpp:141] Deleted player
Jul 07 02:57:45 ip-172-31-5-62 MasterServer[18353]: [07-07-24 02:57:42 CharacterComponent.cpp:378] Time since last save: 0
Jul 07 02:57:45 ip-172-31-5-62 MasterServer[18353]: [07-07-24 02:57:42 Character.cpp:314] 2:GenuineUsefulNonsense Saved character to Database in: 0.001293s
Jul 07 02:57:45 ip-172-31-5-62 MasterServer[18353]: [07-07-24 02:57:42 UserManager.cpp:148] Deleted user 1
Jul 07 02:58:00 ip-172-31-5-62 MasterServer[14130]: [07-07-24 02:57:42 PlayerContainer.cpp:92] Removed user: 1152921508901814274
```

### Reproduction Steps

Finishing the tutorial, build the rocket, and talk to the first NPC.

### Expected Behavior

Destroy bricks, equip items, talk to NPC, with no lag.

### Environment

UBUNTU 22.04.4
RUNNING IN AWS VIRTUAL MACHINE

**Comment by Paulinhoice** [comment] 2024-07-07 04:01
Here the logs:
[ChatServer_1720318137.log](https://github.com/user-attachments/files/16118077/ChatServer_1720318137.log)
[MasterServer_1720318132.log](https://github.com/user-attachments/files/16118078/MasterServer_1720318132.log)
[WorldServer_1100_3_1720320498.log](https://github.com/user-attachments/files/16118079/WorldServer_1100_3_1720320498.log)

**Comment by EmosewaMC** [comment] 2024-07-07 07:22
likely duplicate of #1334

**Comment by Paulinhoice** [comment] 2024-07-07 15:00
THANK YOU

**Closed** 2024-07-07 15:00 UTC
Labels: bug, P-needs-investigation
