### ISSUE TITLE
BUG: Forbidden Valley Wind Lift Not Working

### ISSUE THREAD

**Issue by Phoenyx11** [DarkflameUniverse/DarkflameServer#459] opened 2022-02-20 21:05 UTC
I am having the same issues as people in #72 and #63. The Forbidden Valley wind lift is not working and the gate is not stopping players. I am running the server on Linux.

**Comment by averysumner** [comment] 2022-02-20 21:59
What casing are the lutriggers files in your map folders named in? Is it variable or all lowercase?

**Comment by Phoenyx11** [comment] 2022-02-28 00:07
They're all lowercase. Should they be variable?

**Comment by Phoenyx11** [comment] 2022-03-27 21:16
@averysumner let me know if you need any more information from me.

**Comment by EmosewaMC** [comment] 2022-04-27 09:39
Would you be able to confirm the server version you are running on?  This issue doesn't have a template which hints to me it may have been awhile since you updated your server.

**Comment by Phoenyx11** [comment] 2022-04-30 19:21
Sorry, what command should I run to check this @EmosewaMC? I did do a pull and rebuild before I posted the original and after I asked if the lutriggers should be variable if that helps.

**Comment by EmosewaMC** [comment] 2022-04-30 19:29
Are you using your own fork of DLU?  Or are you just cloning the main branch?  
The command to get your commit hash is `git rev-parse --short HEAD`
If you are forking this to your own branch also remember to update your server by fetching upstream through the form repository page.

**Comment by Phoenyx11** [comment] 2022-04-30 22:50
I am cloning the main branch. I just fetched the latest updates and the problem is still there. My commit hash is ```12ae6a5```.

**Comment by Phoenyx11** [comment] 2022-04-30 23:14
Sorry for responding so late, I just wanted to make sure with the new pull it still wasn't working.

**Comment by EmosewaMC** [comment] 2022-04-30 23:32
> Sorry for responding so late, I just wanted to make sure with the new pull it still wasn't working.

Gotcha.  Could you confirm whether or not you have unzipped the nav meshes as is stated in the github readme?

Unzip the navmeshes [here](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/resources/navmeshes.zip) and place them in `build/res/maps/navmeshes`

**Comment by EmosewaMC** [comment] 2022-05-01 01:57
> I believe they are unzipped, it should just be a collection of .bin files right?

yes thats correct - just trying to eliminate any possible causes.  

What exactly is the naming of your lutriggers files?

The tool lcdr has apparently changes the casing for these and if they are wrong these may not be loaded.
<img width="472" alt="Screen Shot 2022-04-30 at 6 56 54 PM" src="https://user-images.githubusercontent.com/39972741/166128924-7d7e8de2-b45e-4f9a-95e3-476c4e308c5e.png">
r

**Comment by Phoenyx11** [comment] 2022-05-01 06:12
Ohhh, that might be it, the ones I have contain a ```.xml``` after the ```.lutriggers```. Would removing that extension fix it? And would I have to do that for all of the ```.lutriggers```?

**Comment by EmosewaMC** [comment] 2022-05-01 06:32
You could try that. Not sure if that's gonna fix it though.  If it doesn't, try getting the files from an unpacked client instead.

**Comment by Phoenyx11** [comment] 2022-05-01 17:19
Ok I will give it a try, strange thing is I did get the files from an unpacked client though.

**Comment by Phoenyx11** [comment] 2022-05-01 18:13
Just tried removing the ```.xml``` from the forbidden valley crevice lutrigger, unfortunately that didn't work. I'm not sure if it needs to be applied to all the triggers or if the server needs to be rebuilt after the change, but just changing the file extension doesn't fix it.

**Comment by EmosewaMC** [comment] 2022-05-01 23:00
> Just tried removing the `.xml` from the forbidden valley crevice lutrigger, unfortunately that didn't work. I'm not sure if it needs to be applied to all the triggers or if the server needs to be rebuilt after the change, but just changing the file extension doesn't fix it.

What i know would fix the issue is using an unpacked clients files instead of the packed client unpacked with a tool.  Not sure why the tool causes an issue but an unpacked clients files always work correctly.

**Comment by codeshaunted** [comment] 2022-05-02 16:42
> > Sorry for responding so late, I just wanted to make sure with the new pull it still wasn't working.
> 
> Gotcha. Could you confirm whether or not you have unzipped the nav meshes as is stated in the github readme?
> 
> Unzip the navmeshes [here](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/resources/navmeshes.zip) and place them in `build/res/maps/navmeshes`

Navmeshes are unrelated.

> Ohhh, that might be it, the ones I have contain a `.xml` after the `.lutriggers`. Would removing that extension fix it? And would I have to do that for all of the `.lutriggers`?

There should not be a .xml after .lutriggers. How were these extracted?

**Comment by Phoenyx11** [comment] 2022-05-02 17:07
> > > Sorry for responding so late, I just wanted to make sure with the new pull it still wasn't working.
> > 
> > 
> > Gotcha. Could you confirm whether or not you have unzipped the nav meshes as is stated in the github readme?
> > Unzip the navmeshes [here](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/resources/navmeshes.zip) and place them in `build/res/maps/navmeshes`
> 
> Navmeshes are unrelated.
> 
> > Ohhh, that might be it, the ones I have contain a `.xml` after the `.lutriggers`. Would removing that extension fix it? And would I have to do that for all of the `.lutriggers`?
> 
> There should not be a .xml after .lutriggers. How were these extracted?

To be honest I do not remember. I have made a server on a few different platforms so I just transferred the necessary files (such as the navmeshes) from one platform to the next. I believe though that the maps folder and all the files in it are created with the git pull. If it is not, it likely was the fact that I transferred some files from my M1 Mac, and used the ARM64 fork for that one. Is there a way to replace those files with the correct extension? Or should I just remove the ```.xml``` from the file names?

**Comment by EmosewaMC** [comment] 2022-05-02 22:46
> Navmeshes are unrelated.

I recalled navmeshes getting updated at some point a loooong time ago and thought that might be the issue at the time but realized after looking at some other issues that its unrelated to that.  Good that i have confirmation though

**Comment by EmosewaMC** [comment] 2022-05-02 22:48
> > > > Sorry for responding so late, I just wanted to make sure with the new pull it still wasn't working.
> > > 
> > > 
> > > Gotcha. Could you confirm whether or not you have unzipped the nav meshes as is stated in the github readme?
> > > Unzip the navmeshes [here](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/resources/navmeshes.zip) and place them in `build/res/maps/navmeshes`
> > 
> > 
> > Navmeshes are unrelated.
> > > Ohhh, that might be it, the ones I have contain a `.xml` after the `.lutriggers`. Would removing that extension fix it? And would I have to do that for all of the `.lutriggers`?
> > 
> > 
> > There should not be a .xml after .lutriggers. How were these extracted?
> 
> To be honest I do not remember. I have made a server on a few different platforms so I just transferred the necessary files (such as the navmeshes) from one platform to the next. I believe though that the maps folder and all the files in it are created with the git pull. If it is not, it likely was the fact that I transferred some files from my M1 Mac, and used the ARM64 fork for that one. Is there a way to replace those files with the correct extension? Or should I just remove the `.xml` from the file names?

If the file was extracted as a .xml file instead off a .lutriggers file then changing the extension won't do anything.  You could try just removing the extension on all .lutriggers files but if that doesnt work you will need the files to be extracted such that they have the extension .lutriggers and nothing else.

**Comment by Phoenyx11** [comment] 2022-05-03 15:47
> > > > > Sorry for responding so late, I just wanted to make sure with the new pull it still wasn't working.
> > > > 
> > > > 
> > > > Gotcha. Could you confirm whether or not you have unzipped the nav meshes as is stated in the github readme?
> > > > Unzip the navmeshes [here](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/resources/navmeshes.zip) and place them in `build/res/maps/navmeshes`
> > > 
> > > 
> > > Navmeshes are unrelated.
> > > > Ohhh, that might be it, the ones I have contain a `.xml` after the `.lutriggers`. Would removing that extension fix it? And would I have to do that for all of the `.lutriggers`?
> > > 
> > > 
> > > There should not be a .xml after .lutriggers. How were these extracted?
> > 
> > 
> > To be honest I do not remember. I have made a server on a few different platforms so I just transferred the necessary files (such as the navmeshes) from one platform to the next. I believe though that the maps folder and all the files in it are created with the git pull. If it is not, it likely was the fact that I transferred some files from my M1 Mac, and used the ARM64 fork for that one. Is there a way to replace those files with the correct extension? Or should I just remove the `.xml` from the file names?
> 
> If the file was extracted as a .xml file instead off a .lutriggers file then changing the extension won't do anything. You could try just removing the extension on all .lutriggers files but if that doesnt work you will need the files to be extracted such that they have the extension .lutriggers and nothing else.

Ok sounds good. Can I take the map data from the client files and just put that in the server files, or is there another way I need to get them?

**Comment by codeshaunted** [comment] 2022-05-03 18:00
> > > > > > Sorry for responding so late, I just wanted to make sure with the new pull it still wasn't working.
> > > > > 
> > > > > 
> > > > > Gotcha. Could you confirm whether or not you have unzipped the nav meshes as is stated in the github readme?
> > > > > Unzip the navmeshes [here](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/resources/navmeshes.zip) and place them in `build/res/maps/navmeshes`
> > > > 
> > > > 
> > > > Navmeshes are unrelated.
> > > > > Ohhh, that might be it, the ones I have contain a `.xml` after the `.lutriggers`. Would removing that extension fix it? And would I have to do that for all of the `.lutriggers`?
> > > > 
> > > > 
> > > > There should not be a .xml after .lutriggers. How were these extracted?
> > > 
> > > 
> > > To be honest I do not remember. I have made a server on a few different platforms so I just transferred the necessary files (such as the navmeshes) from one platform to the next. I believe though that the maps folder and all the files in it are created with the git pull. If it is not, it likely was the fact that I transferred some files from my M1 Mac, and used the ARM64 fork for that one. Is there a way to replace those files with the correct extension? Or should I just remove the `.xml` from the file names?
> > 
> > 
> > If the file was extracted as a .xml file instead off a .lutriggers file then changing the extension won't do anything. You could try just removing the extension on all .lutriggers files but if that doesnt work you will need the files to be extracted such that they have the extension .lutriggers and nothing else.
> 
> Ok sounds good. Can I take the map data from the client files and just put that in the server files, or is there another way I need to get them?

Map data should come from the client. You can get more information on this by reading the instructions for server setup listed in the README. You can either use extracted files from a packed client or you can use files directly from an unpacked client.

**Comment by Phoenyx11** [comment] 2022-05-04 03:03
> > > > > > > Sorry for responding so late, I just wanted to make sure with the new pull it still wasn't working.
> > > > > > 
> > > > > > 
> > > > > > Gotcha. Could you confirm whether or not you have unzipped the nav meshes as is stated in the github readme?
> > > > > > Unzip the navmeshes [here](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/resources/navmeshes.zip) and place them in `build/res/maps/navmeshes`
> > > > > 
> > > > > 
> > > > > Navmeshes are unrelated.
> > > > > > Ohhh, that might be it, the ones I have contain a `.xml` after the `.lutriggers`. Would removing that extension fix it? And would I have to do that for all of the `.lutriggers`?
> > > > > 
> > > > > 
> > > > > There should not be a .xml after .lutriggers. How were these extracted?
> > > > 
> > > > 
> > > > To be honest I do not remember. I have made a server on a few different platforms so I just transferred the necessary files (such as the navmeshes) from one platform to the next. I believe though that the maps folder and all the files in it are created with the git pull. If it is not, it likely was the fact that I transferred some files from my M1 Mac, and used the ARM64 fork for that one. Is there a way to replace those files with the correct extension? Or should I just remove the `.xml` from the file names?
> > > 
> > > 
> > > If the file was extracted as a .xml file instead off a .lutriggers file then changing the extension won't do anything. You could try just removing the extension on all .lutriggers files but if that doesnt work you will need the files to be extracted such that they have the extension .lutriggers and nothing else.
> > 
> > 
> > Ok sounds good. Can I take the map data from the client files and just put that in the server files, or is there another way I need to get them?
> 
> Map data should come from the client. You can get more information on this by reading the instructions for server setup listed in the README. You can either use extracted files from a packed client or you can use files directly from an unpacked client.

Ok awesome thanks I will give that a try.

**Comment by EmosewaMC** [comment] 2022-05-10 20:54
Closing since this is a misconfiguration.  Please reopen if issue persists with the correct client dependencies.

**Closed by EmosewaMC** 2022-05-10 20:54 UTC
Labels: bug, P-misconfiguration, A-game
