### ISSUE TITLE
BUILD: Docker does not copy over client files

### ISSUE THREAD

**Issue by WildclawAvali** [DarkflameUniverse/DarkflameServer#612] opened 2022-07-05 16:12 UTC
### Make sure you've done the following:

- [X] I have read the [installation guide](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/README.md).

### DarkflameServer Version

8cdb388

### Platform

Windows

### Architecture

ARM

### Error Logs

<details>

[05-07-22 15:55:42] [WorldServer] ./res/CDServer.sqlite could not be opened

</details>

Cant change admin password and i dont know the default ones

**Comment by WildclawAvali** [comment] 2022-07-05 17:29
but how do i fix it... i did everything from the dockers guide.. and there is not an res folder or cdserver file.. and i cant make one...

**Comment by EmosewaMC** [comment] 2022-07-05 17:35
> but how do i fix it... i did everything from the dockers guide.. and there is not an res folder or cdserver file.. and i cant make one...

Which docker setup guide did you follow just to make sure?  I noticed some issues with docker because it literally just didnt copy over any client files and I had to do so manually.  @TheNoim Perhaps you could shed light on this issue?  Were you experiencing the docker setup not copying over the client files on dlu main?

**Comment by WildclawAvali** [comment] 2022-07-05 17:46
sorry, im very new to github xd

**Comment by EmmettPeck** [comment] 2022-08-14 14:30
Having the same issue on Ubuntu when trying to setup admin account executing `docker compose exec darkflame /app/MasterServer -a` .
This occurred after a successful build.

#### Error Message
<details>
[14-08-22 14:20:43] [WorldServer] ./res/CDServer.sqlite could not be opened
</details>

**Comment by prhiggins** [comment] 2022-10-05 00:45
If anybody is still having this problem, check whether you are using the **Packed** or **Unpacked** client. I was getting this error using the unpacked client and was able to fix it here: https://github.com/DarkflameUniverse/DarkflameServer/issues/377#issuecomment-1013780987

After setting up your client directory structure as follows, you will have to rebuild. Executing `docker compose exec darkflame /app/MasterServer -a` then worked for me.

This more or less looks like a duplicate of #377, hope that works for anyone encountering this problem.

**Closed** 2023-01-07 05:04 UTC
Labels: build, P-medium, A-docker
