### ISSUE TITLE
Quick Builds sometimes break and cannot be built until the next opportunity.

### ISSUE THREAD

**Issue by EGOFALCON** [DarkflameUniverse/DarkflameServer#206] opened 2021-12-13 13:31 UTC
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

There is a chance in the game that when I go to do a quick build, whether it's create a bouncer pad or my Assembly Turret, that it will not allow me to actually perform the quick build. It instead labels that there is no imagination needed when asking me to press and hold shift, and when I do press and hold shift, nothing happens.

This is more prominent in high movement instances but can also happen at random, sometimes when even getting hit or pressing SHIFT too fast.

### Reproduction steps

Go to any quick build that will be exposed to enemies.
When you go to make the build, before you do so, move or get hit by an enemy, it should reproduce the issue.

If not, another way is to press Shift right as the build is ready to be built. It seems to break it as-well.

### Expected Behavior

You can quick build without interruption or having to wait to break the model again, or wait until the Assembly turret is off cooldown.

### Environment

Ubuntu on Windows

**Comment by MickVermeulen** [comment] 2021-12-13 13:34
Duplicate of #122, closing.

**Closed by MickVermeulen** 2021-12-13 13:34 UTC
Labels: bug, triage
