### ISSUE TITLE
BUG: Going to title screen after loading into a world causes the server IP to be set to localhost

### ISSUE THREAD

**Issue by Dragonisser** [DarkflameUniverse/DarkflameServer#154] opened 2021-12-09 18:21 UTC
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

If you disconnect or timeout from a server and try to login again it only leads to following error. There is also no error or information in the log saying that something didnt worked.

![image](https://user-images.githubusercontent.com/4233773/145453319-cba1f86a-1aa2-4675-a06a-bb49b252621e.png)

### Reproduction steps

- Connect to server
- Logout
- Try to log in again

### Expected Behavior

Can log in 

### Environment

Operating System: Ubuntu 20.04.2 LTS
Kernel: Linux 5.4.124-1-pve
Architecture: x86-64

**Comment by SilberComic** [comment] 2021-12-09 18:30
it changes the login ip to 127.0.0.1 for me but i have the same issue

**Comment by Dragonisser** [comment] 2021-12-09 18:35
> it changes the login ip to 127.0.0.1 (and im joining a vps, so not localhost) for me but i have the same issue

Youre right, i did noticed that before but thought its been like that the whole time.

**Comment by Wincent01** [comment] 2021-12-09 18:46
This has been a known issue for awhile. We are unsure what courses it; if it is something the server is involved with or not is unknown.

**Comment by Pr3roxDLC** [comment] 2021-12-09 21:31
@Wincent01 any idea what a cause for frequent player timeouts could be?

**Comment by Wincent01** [comment] 2021-12-09 21:35
If you’re on a slower connection try disabling the anti-speedhack in your worldconfig.ini file and see if the situation improves.
https://github.com/DarkflameUniverse/DarkflameServer/blob/82a1c8a765f73244c88bb088a16db8e57808c69a/resources/worldconfig.ini#L49

**Comment by Pr3roxDLC** [comment] 2021-12-10 17:32
Im having this issue on a 60ms connection with disable_aint_speedhack set to 1

**Comment by EmosewaMC** [comment] 2022-10-31 04:10
Does this persist on main?

**Comment by EmosewaMC** [comment] 2023-09-25 02:25
This is due to how the client tries to find boot.cfg after you login.  The issue is fixed by either using a packed client or by adding a boot.cfg into the res directory for unpacked clients.  Won't fix on our and as this is a client bug.

**Closed by EmosewaMC** 2023-09-25 02:25 UTC
Labels: bug, P-Client-Bug

**Comment by EmosewaMC** [comment] 2023-09-25 02:42
This issue is also solved by renaming the folder legouniverse.exe is in to `client`
