### ISSUE TITLE
BUG: Shuriken of Ice crashes Server

### ISSUE THREAD

**Issue by Morthi** [DarkflameUniverse/DarkflameServer#245] opened 2021-12-16 16:36 UTC
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

If you shoot with the Shuriken of Ice against a SOLID Object (not breakable) like a Wall or a Pillar the Server will crash.

### Reproduction steps

-> Use Shuriken of Ice
-> Shoot against a wall or something not breakable
-> Server will crash

### Expected Behavior

-> Server shouldn't crash

### Environment

Ubuntu, WSL 1

https://user-images.githubusercontent.com/31543889/146419765-a9d01e57-419b-4a4e-bb4d-2d0c1f1e6eee.mp4

**Comment by leolion3** [comment] 2021-12-18 12:26
Can you try going into your `WorldServer.cpp` file, putting a `try {` right under the `while (True) {` and a
```
}
catch (const std::exception &e) {
    std::cerr << e.what() << std::endl;
}
```

Before the closing `}` of the loop? (Look at indentation to figure out which one it is)
This will print out the error that is causing the WorldServer to crash

**Comment by Morthi** [comment] 2021-12-19 12:21
I got this.
![FatalError](https://user-images.githubusercontent.com/31543889/146674646-e2ee66be-8c58-447a-a22e-83d26a95a407.png)

**Comment by leolion3** [comment] 2021-12-19 13:21
@Morthi you didn't print the exception clause. Please add the code I wrote and recompile the server. What you are getting is gibberish unless you want to decompile the executeable and read assembly code.

**Comment by Morthi** [comment] 2021-12-20 14:04
I did that, rebuilt it and it is still giving out the gibberish
![try](https://user-images.githubusercontent.com/31543889/146779300-0e41285e-1f7d-4b84-afb9-1cd22dded67d.png)
![catch](https://user-images.githubusercontent.com/31543889/146779334-466dbf8a-aad7-459f-9c50-fdf9e8568bf4.png)

**Comment by leolion3** [comment] 2021-12-21 00:13
Can you do the same thing for the Chat and Master server CPPs?

**Comment by Morthi** [comment] 2021-12-21 17:20
still gibberish

**Comment by leolion3** [comment] 2021-12-21 22:59
That can't be. The exception is originating from WorldServer. Try encasing every `handleSomething` method in s try-catch block qnd see what output you get. Don't forget to rebuild the server.

**Comment by BigSadge** [comment] 2022-01-08 02:41
I am also unable to reproduce, Tried several times at the Ninjago Monastery, same pole as in the video.

Note: This is item 12659 and can be added with  /gmadditem 12659

Environment:
Virtualbox Ubuntu Server VM
Windows Client
AMD Ryzen 3600

**Comment by averysumner** [comment] 2022-01-31 11:43
I am also unable to reproduce. Closing this issue as it is stale and no extra communication has occurred. Reopen it if you’re still encountering this on the latest commit.

**Closed by averysumner** 2022-01-31 11:43 UTC
Labels: bug, priority/needs-investigation
