### ISSUE TITLE
Unable to use shift to build or talk to NPCs

### ISSUE THREAD

**Issue by mwolverine63** [DarkflameUniverse/DarkflameServer#123] opened 2021-12-08 06:43 UTC
When I first log into the game, I can use shift to talk to NPCs.

After a few minutes, shift will stop working. I have to log out and log back in to get shift to start working again, so I can interact with NPCs or build.

I am running an Ubuntu server on a macOS client

**Comment by IAmVolvic** [comment] 2021-12-08 07:13
This is the same as https://github.com/DarkflameUniverse/DarkflameServer/issues/122

**Comment by averysumner** [comment] 2021-12-08 07:49
> This is the same as #122

This sounds like a client issue unrelated to #122.

**Comment by Pr3roxDLC** [comment] 2021-12-08 22:49
Im experiencing the same problem with players "timing out" randomly, no disconnects, just the client getting no more packets from the server, checked it with WireShark on Windows for the client and tshark on my vps and both showed the server just stopping sending packets to the client while the client still tries to talk back to the client

For me the best way to fix this is by logging back out, and either just logging back in, or logging out, logging back in and when it gets stuck while loading closing the game, as this causes the server to recieve a "disconnect packet" resulting in the server actually removing the player and allowing them to log back it

Server Running on a Ubuntu 18.04 VPS using MariaDB, the source code being built for the Normal Client and the clients using lcrd's unpacked client

**Comment by Pr3roxDLC** [comment] 2021-12-08 23:10
@mwolverine63 does it also cause your game to stop dropping stuff when killing enemies/smashing stuff?

**Comment by mwolverine63** [comment] 2021-12-10 05:31
Yes, that happens too.

**Comment by IAmJacket** [comment] 2021-12-10 08:16
This is currently happening to me. Stuck trying to talk to Sky Lane. 

Pressing shift to interact with an NPC or to build will not do anything, and immediately afterwards broken objects will not drop coins or loot. Broken items will then reappear a second after breaking as if nothing happens. All UI components seem to stop working as well, attempting to change your Minifigure will not result in exiting the server, you'll still be playing.

**Comment by Idkahn** [comment] 2021-12-10 10:31
I am running into this issue too. From what I can tell through Wireshark, there are some packets sent from the server while it's frozen but only when I try to interact with or attack something, and they seemingly do nothing in game. Other than that, nothing comes in from the server.

There are also messages like `[StunBehavior]: Failed to find target (##################)!` that are logged to the server console when I attack something, where the number is what I assume is the id of the object or enemy.

**Comment by averysumner** [comment] 2021-12-14 17:15
We've been unable to reproduce any of this behavior. @Idkahn the
`StunBehavior` messages are unrelated.

**Comment by averysumner** [comment] 2022-01-31 11:59
Has this issue persisted?

**Comment by Idkahn** [comment] 2022-02-01 01:59
I just set up a server again from scratch to test this and I can confirm that it's still an issue for me. 

When I load into the Venture Explorer with a new character, almost immediately the ship part boxes stop dropping anything, npcs stop responding, and the kill zone doesn't work.

**Comment by averysumner** [comment] 2022-02-02 01:17
> I just set up a server again from scratch to test this and I can confirm that it's still an issue for me.
> 
> When I load into the Venture Explorer with a new character, almost immediately the ship part boxes stop dropping anything, npcs stop responding, and the kill zone doesn't work.

What hardware do you have dedicated to your VPS? And what client are you using? This almost sounds like your server doesn’t have enough resources and is lagging behind, or your client is entirely broken. Please send client and server logs.

**Comment by Idkahn** [comment] 2022-02-02 10:05
I currently have the server on an AWS Lightsail instance running Amazon Linux 2, with 2 vCPUs and 4 GB of Ram. Nothing else is currently running on it. I also had the same problem previously when testing with a WSL2 Ubuntu install, though I don't remember what resources I had allocated to it. 

The client I'm using to both play and build the server is lcdr's unpacked client.

Here's all the logs from the server:
[WorldServer_0_0_1643792358.log](https://github.com/DarkflameUniverse/DarkflameServer/files/7985180/WorldServer_0_0_1643792358.log)
[WorldServer_1000_1_1643792358.log](https://github.com/DarkflameUniverse/DarkflameServer/files/7985181/WorldServer_1000_1_1643792358.log)
[AuthServer_1643792358.log](https://github.com/DarkflameUniverse/DarkflameServer/files/7985182/AuthServer_1643792358.log)
[ChatServer_1643792358.log](https://github.com/DarkflameUniverse/DarkflameServer/files/7985183/ChatServer_1643792358.log)
[MasterServer_1643792358.log](https://github.com/DarkflameUniverse/DarkflameServer/files/7985184/MasterServer_1643792358.log)

and the client:
[log_legouniverse_02-02-22_00-59-22__49828.log](https://github.com/DarkflameUniverse/DarkflameServer/files/7985187/log_legouniverse_02-02-22_00-59-22__49828.log)

If it helps, interactions stopped sometime around 01:01:00, and my client got kicked to the login screen around 01:01:30. 

It also spawned me inside of the kill zone when I logged in which is where I had logged out in the previous attempt, meaning that it probably still saves my position when everything else stops working.

**Comment by EmosewaMC** [comment] 2022-07-17 00:08
Does this persist on main?

**Comment by EmosewaMC** [comment] 2022-10-30 08:18
This issue has not been updated on whether or not it persists on main.  Please re-open if this is still an issue

**Closed by EmosewaMC** 2022-10-30 08:18 UTC
Labels: bug, help wanted, P-medium
