### ISSUE TITLE
MasterServer not Self Killing

### ISSUE THREAD

**Issue by CitrusHappy** [DarkflameUniverse/DarkflameServer#82] opened 2021-12-07 06:52 UTC
server should self kill its own process when not properly exited via esc commands like CTRL+Z, otherwise will cause issues with connecting to SQL database.

**Comment by QuirkyTurtle101** [comment] 2021-12-07 13:45
Supposing that you've improperly exited - how do you recover from it? My server is currently borked for this reason, and won't start properly.

**Comment by CitrusHappy** [comment] 2021-12-07 22:52
yup, I'm having this exact issue as well, pretty sure it's a problem in the code and not the way our servers were set up. if you use the ps command you can see all the past processes that have been suspended but not killed. you can kill them using the kill command "kill <PIQ>"

**Comment by DarwinAnim8or** [comment] 2021-12-07 23:52
MasterServer kills it's and other WorldServer instances on Linux if you do Ctrl+C on it.
You can also go in-game and user /shutdownuniverse

**Comment by MickVermeulen** [comment] 2021-12-09 18:50
You should close the server with Ctrl+C, not with Ctrl+Z, as that just sends it to the background where it _might_ get killed. Closing as I'm not able to reproduce this when using Ctrl+C.

**Closed by MickVermeulen** 2021-12-09 18:50 UTC
