### ISSUE TITLE
BUG: Shooting Gallery can't be started

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#566] opened 2022-05-27 15:34 UTC
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

915b779

### Issue Description

Sometimes, when loading into the Shooting Gallery, there is no start button and you have no option but to leave.
![Lego Universe Screenshot 2022 05 27 - 11 29 45 32](https://user-images.githubusercontent.com/48499798/170731338-0517442c-612e-4fa0-a106-591af262af79.png)

### Reproduction Steps

Not sure exactly how to replicate. Used to happen every time the instance was opened for the first time, but after the major shooting gallery updates months ago it only happens occasionally.

### Expected Behavior

the start button should always appear

### Environment

ubuntu server

**Comment by EmosewaMC** [comment] 2022-05-27 18:00
dupe of #65

**Closed by EmosewaMC** 2022-05-27 18:00 UTC
Labels: bug, triage

**Comment by EmosewaMC** [comment] 2022-05-27 18:04
as an aside - please confirm bugs are not submitted yet before submitting them.  It wastes our time to go and cross reference a bug and creates useless spam.
