### ISSUE TITLE
BUG: First attack on world switch is always fists (unarmed)

### ISSUE THREAD

**Issue by jadebenn** [DarkflameUniverse/DarkflameServer#1280] opened 2023-11-12 22:53 UTC
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

411dce74

### Issue Description

When changing worlds and making an attack, your character will always make one punch with their fists before switching to using their correct attack ability.

### Reproduction Steps

1. Load the game
2. Fly to another world
3. Click to attack

### Expected Behavior

Character should be using the correct attack ability from the start

### Environment

Ubuntu WSL2

**Comment by EmosewaMC** [comment] 2023-11-12 23:17
duplicate of #529

**Closed by EmosewaMC** 2023-11-12 23:17 UTC
Labels: bug, triage

**Comment by jadebenn** [comment] 2023-11-12 23:20
Ah sorry, I did a search and I didn't see it.
