### ISSUE TITLE
BUG: Pets can excavate treasure before required quest

### ISSUE THREAD

**Issue by jadebenn** [DarkflameUniverse/DarkflameServer#1286] opened 2023-11-13 03:02 UTC
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

411dce7

### Issue Description

Pets are not supposed to be able to excavate treasure before completing [Bella Pepper's "Lost Tags" quest.](https://explorer.lu/missions/842)

https://github.com/DarkflameUniverse/DarkflameServer/assets/9892985/0a29f46b-6d19-4865-901c-e087c222d86d

### Reproduction Steps

1. Play a character that has not completed Bella Pepper's quest
2. Excavate treasure using a pet

### Expected Behavior

Pets should check for [this quest's completion](https://explorer.lu/missions/842) and not excavate treasure beforehand.

### Environment

WSL Ubuntu

**Comment by jadebenn** [comment] 2023-11-13 03:03
@EmosewaMC This seems like another one I might be able to handle myself. I'll just need to find where the interaction is handled and add a check for mission completion.

**Comment by MustacheMan2** [comment] 2023-11-13 03:31
Duplicate of #535

**Closed** 2023-11-13 03:43 UTC
Labels: bug, triage
