### ISSUE TITLE
BUG: Sentinel Combat Challenge Red Target Dummy takes no damage

### ISSUE THREAD

**Issue by MichaelFedora** [DarkflameUniverse/DarkflameServer#264] opened 2021-12-18 18:36 UTC
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

In the sentinel combat challenge, you can only get to a little over 100 points because the red target dummy (which, when taking damage, damages other players), does not receive any damage. This makes a couple achievements unachievable.

### Reproduction steps

- Play the Sentinel Combat Challenge in Nexus Tower
- Get up to a little over 100 points to start getting the Red Target Dummies
- Get stuck because you cannot destroy it

### Expected Behavior

That you should be able to destroy the red target dummy.

### Environment

Window client / ubuntu server

**Comment by EmosewaMC** [comment] 2021-12-20 10:20
It looks like specifically in the code, the issue is with [dummy 13830](https://github.com/DarkflameUniverse/DarkflameServer/blob/f7858ab18354bd11ae5cc0e53e3716ee92afae3f/dScripts/NtCombatChallengeServer.h#L31).

**Comment by EmosewaMC** [comment] 2022-01-12 08:23
Updating on this; Issue is a missing script for this specific Entity.  Working on a fix

**Comment by MichaelFedora** [comment] 2022-01-12 17:43
Thanks for all the hard work you are doing @EmosewaMC =)

**Comment by EmosewaMC** [comment] 2022-02-11 04:26
So the dummy is actually taking damage, but it's health is so high you will never smash it in normal gameplay.  It also has its own cdserver script which overrides the custom script.  This is addressed in the pr above

**Closed** 2022-03-30 21:21 UTC
Labels: bug, P-low
