### ISSUE TITLE
BUG: Property UI displays properties from all locations

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#473] opened 2022-03-19 16:26 UTC
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

All properties in the universe will display on any property interface. Could be related to some properties just not displaying?
![Capture](https://user-images.githubusercontent.com/48499798/159129569-72fd347e-40c7-4f5c-9559-ecec006a6f18.PNG)
![2](https://user-images.githubusercontent.com/48499798/159129574-741bd375-61b4-4a23-8e71-4e48c23db09a.PNG)

### Reproduction steps

Have a sizeable amount of users create properties across the universe and approve them all. This will start happening.

### Expected Behavior

Properties shown should be exclusive to that instance.

### Environment

Ubuntu server

**Comment by EmosewaMC** [comment] 2022-03-20 00:15
dupe of #323

**Closed** 2022-03-20 02:03 UTC
Labels: bug, triage
