### ISSUE TITLE
BUG: Random Crashing During Rocket Launch

### ISSUE THREAD

**Issue by AugustRenders** [DarkflameUniverse/DarkflameServer#1138] opened 2023-07-15 00:53 UTC
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

Unknown, possibly the latest

### Issue Description

Most of the time, this doesn't happen, but sometimes the game crashes when I'm launching my rocket to another world.

### Reproduction Steps

Play the game as you usually would. Go from world to world, doing whatever. You should eventually find that the game crashes.

### Expected Behavior

When you launch your rocket, you should travel between worlds as normal without getting interrupted by crashes.

### Environment

Windows 10

**Comment by EmosewaMC** [comment] 2023-07-15 01:37
Do not create issues and link external servers.  Doing so again will get you banned.

We will not accept bug reports if you cannot report the actual server version.
With your previous comment, that server is not valid for bug reports as the maintainer does not actually update their server.  

Random crashes are not something that will be investigated or fixed without a reproduction.

**Comment by NealSpellman** [comment] 2023-07-15 19:18
Closing this issue due to external server and no details, as mentioned above. Please refrain from posting issues that are related to servers you do not host or have specifics of. (server version, etc)

**Closed by NealSpellman** 2023-07-15 19:18 UTC
Labels: bug, invalid
