### ISSUE TITLE
BUG: Placing new ship parts over old ship parts does not return them to the inventory while in ship editor

### ISSUE THREAD

**Issue by Virepri** [DarkflameUniverse/DarkflameServer#285] opened 2021-12-21 10:55 UTC
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Ship parts are not returned to the inventory until exiting ship editing.

If I place one ship part over another (e.g. the blue ship middle over the pink ship middle), the pink ship middle will not be returned to my inventory until I cancel or otherwise quit editing my ship.

This sounds _similar_ to #159; but it could be different.

### Reproduction steps

1) Place down a ship part.
2) Place down an overlapping ship part.
3) Profit.

### Expected Behavior

The replaced ship part should be returned to the inventory instead of temporarily destroyed.

### Environment

Debian Linux 11 under lxc running on Proxmox

**Comment by Wincent01** [comment] 2021-12-21 12:31
Duplicate of #243

**Closed by Wincent01** 2021-12-21 12:31 UTC
Labels: bug, triage
