### ISSUE TITLE
BUG: Wisp Lee mission not working

### ISSUE THREAD

**Issue by MapleDappy** [DarkflameUniverse/DarkflameServer#466] opened 2022-03-04 19:22 UTC
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

When you go to complete the quest "talk to wisp lee in avant gardens" it does not work and you are stuck in a loop of accepting a quest from lee. [https://youtu.be/_19-5lWGbvM](url) He also does not give you the vacuum to complete the quest nor does it prompt the quest to start.

### Reproduction steps

Go to forbidden valley and accept the quest from numb chuck to talk to wisp lee. When you arrive you should have a chest showing a quest complete icon. When you talk to wisp lee you should not be able to complete the quest.

### Expected Behavior

I would expect that because he is accepting and giving a quest at the same time, he would have the multiple quest menu.

### Environment

Windows 10 using Virtualbox ubuntu64bit

**Comment by EmosewaMC** [comment] 2022-03-04 21:46
Dupe of #296

**Comment by NealSpellman** [comment] 2022-03-15 01:18
Closing since, as mentioned above, this is a duplicate.

**Closed by NealSpellman** 2022-03-15 01:18 UTC
Labels: bug, triage
