### ISSUE TITLE
DOC: mention adding toplevel IP to `ini` files in docker README

### ISSUE THREAD

**Issue by floington500** [DarkflameUniverse/DarkflameServer#1220] opened 2023-10-15 03:39 UTC
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that the documentation is wrong or missing on the latest version of the main branch of DarkflameServer

### Location of the documentation

https://github.com/DarkflameUniverse/DarkflameServer/blob/main/Docker.md

### Documentation problem

The directions fail to mention that `ini` files in `resources/` need to be updated with the upstream IP address of the host device. They are initally valued with just `localhost` which causes issues because docker containers are all assigned their own unique IP address.

Without doing this, on login the user will be prompted with the same screen that says "Enter nickname/password and hit "Sign In" to continue." which looks like this:

![image](https://github.com/DarkflameUniverse/DarkflameServer/assets/109321368/fcd345c6-6eb6-478c-a257-f999e46f4f9b)

The user *could* figure out the solution through the process of reading through the normal installation instructions like I did, but that is rather complicated and misleading considering it could save hours of time by just adding one step.

### Suggested fix for documentation

Add a step before the build process (4) which would let the user know about needing to insert IP address values in the `ini` files. This could look something like this:

...
3. Update other values in the `.env` file as needed (be sure to update passwords!)
4. The last part of the configuration is to change any value of `localhost` in `ini` files  to the IP address of your device.
5. Run docker `compose up -d --build`
...

I would love to see this get fixed because it probably costed me an hour or two to figure out what the issue was and to recompile the server, thanks.

**Comment by EmosewaMC** [comment] 2023-10-15 08:45
There is no need to modify the ini files in the repo.  the .env file should be doing that.  Is the .env value not being updated?

**Comment by EmosewaMC** [comment] 2023-10-15 08:47
The line here should be updating the ini files with the ip provided
https://github.com/DarkflameUniverse/DarkflameServer/blob/c6087ce77ac2222738aafdf68c23da81e0d1e606/.env.example#L11

**Comment by EmosewaMC** [comment] 2023-10-15 10:45
I have confirmed that on the main branch the .env file correctly updates the sharedconfig.ini file with the external ip address and no ini modification is necessary.  Please consider double checking your configuration and verify that the external ip noted above in your .env file does not say localhost.

**Comment by EmosewaMC** [comment] 2023-10-22 10:36
Closing due to being a non-issue.

**Closed by EmosewaMC** 2023-10-22 10:36 UTC
Labels: P-misconfiguration, A-docker
