### ISSUE TITLE
Can't load back into game on one of my characters

### ISSUE THREAD

**Issue by BustosAndrew** [DarkflameUniverse/DarkflameServer#80] opened 2021-12-07 04:54 UTC
I was trying to do the satellite mission from nexus tower where I put a satellite on my block yard property. This is the property where you take a rocket from avant gardens. Every time it loads it goes from 97%-99% before kicking me back to login screen, at which point I have to restart the client to log back in. My character is currently stuck trying to load into Block Yard every time I try logging back in. Apparently this is also happening for a different player on a different server. Could this be related to issue #31?

**Comment by NealSpellman** [comment] 2021-12-07 06:11
There's no details here; are you getting anything in the server logs? Or client logs? Do all properties have this issue?

**Comment by BustosAndrew** [comment] 2021-12-07 06:12
@NealSpellman where do I find client logs?

**Comment by BustosAndrew** [comment] 2021-12-07 06:19
[log_legouniverse_12-06-21_22-06-16__7020.log](https://github.com/DarkflameUniverse/DarkflameServer/files/7665916/log_legouniverse_12-06-21_22-06-16__7020.log)
Latest client log.

**Comment by BustosAndrew** [comment] 2021-12-08 05:16
Update: more people on the same server as me ran into the same issue when trying to load into a property. Will get server logs soon.

**Comment by lroberge** [comment] 2021-12-08 21:23
I'm having this exact same issue on my server. We didn't have any issues fighting the Spider Queen, nor during the property building tutorial immediately after - but after going back to Avant Gardens, attempting to return to the Block Yard property kicks us to the login screen and prevents us from loading in with that character. (Haven't tested with any other properties)

We do have a temporary solution for getting characters out - search for instances of the Block Yard zone ID `1150` in their corresponding `charxml` entry in the DB and replace the first two instances with some other zone ID, e.g. `1100` (for Avant Gardens).

This is occurring both when the server is hosted on a Google Cloud Platform VM and my local WSL installation - both Ubuntu 20.04, with MariaDB 10.3.32. All of the CDServer.sqlite migration patches have been applied, and I've played with the PATCHSERVER and UGCSERVER options in boot.cfg - they don't change the outcome, no matter whether they point to localhost or to a server created with `sudo python -m http.server 80` as suggested in the readme.

**Comment by MickVermeulen** [comment] 2021-12-09 18:51
Could you guys also share your server logs?

**Comment by averysumner** [comment] 2022-01-31 12:00
Does this issue persist on the latest commit?

**Comment by BustosAndrew** [comment] 2022-02-07 09:54
> Does this issue persist on the latest commit?

I'll ask my server owner.

**Comment by Racater** [comment] 2022-02-23 22:56
@averysumner yes, the issue is still there

**Comment by Racater** [comment] 2022-04-05 16:19
it seems to be the same issue as #156

**Comment by EmosewaMC** [comment] 2022-05-04 11:46
Closing since this is a dupe of #156 and that issue has more detailed reports.  Please ensure you have followed the UGC server setup process in the README as when done correctly this will resolve the issue.

**Closed by EmosewaMC** 2022-05-04 11:46 UTC
Labels: bug, P-medium
