### ISSUE TITLE
Corrupted Sentry invincible at Return to Venture 

### ISSUE THREAD

**Issue by HorizonFade** [DarkflameUniverse/DarkflameServer#113] opened 2021-12-08 01:57 UTC
https://user-images.githubusercontent.com/16822185/145134626-e5118ad9-50ed-4213-8e7e-9467b019f9c5.mp4

**Comment by NealSpellman** [comment] 2021-12-08 02:11
Duplicate of #54. Closing.

**Closed by NealSpellman** 2021-12-08 02:11 UTC
