### ISSUE TITLE
Return to Venture Explorer: Mechs not Enemys

### ISSUE THREAD

**Issue by JustProp** [DarkflameUniverse/DarkflameServer#124] opened 2021-12-08 07:30 UTC
Mechs on the Venture Explorer have white names and red health bars, and wont aggro to you nor take damage whatsoever. They wont fight other mobs either, making a quest impossible to finish.

**Comment by averysumner** [comment] 2021-12-08 07:44
Duplicate of #54

**Closed by averysumner** 2021-12-08 07:44 UTC
