### ISSUE TITLE
Chat not working

### ISSUE THREAD

**Issue by basedx32** [DarkflameUniverse/DarkflameServer#61] opened 2021-12-06 20:32 UTC
Tested on a Vultr VPS with all ports open and a home server
OS: Ubuntu 20.04
Database: Mysql 8.0.27 and MariaDB 10.7.1 on docker

Problem: Local chat can not be used, any messages without a slash typed in show a loading button and then a red exclamation mark. Level ups do not show in the chat box either. Only slash commands that do work are /info and /credits, all others do nothing but do not show the red exclamation. Tested using gm levels 0, 1, 9. Others who managed to compile report the same issue but not everyone.

**Comment by averysumner** [comment] 2021-12-06 21:43
Have you confirmed an instance of ChatServer is running?

**Comment by Landshark77** [comment] 2021-12-06 22:08
Seeing the same issue on Ubuntu / MariaDB.

This is the output of the ChatServer log file:

```
[06-12-21 21:37:43] [ChatServer]: Starting Chat server...
[06-12-21 21:37:43] [ChatServer]: Version: 1.0
[06-12-21 21:37:43] [ChatServer]: Compiled on: Sun Dec  5 21:43:20 2021
[06-12-21 21:37:43] [dServer]: Server is listening on 192.168.1.35:1501 with encryption: 1
[06-12-21 21:37:43] [Server]: Established connection to master
[06-12-21 21:37:43] [ChatServer]: A server is connecting, awaiting user list.
[06-12-21 21:37:43] [ChatServer]: A server is connecting, awaiting user list.
[06-12-21 21:45:22] [PlayerContainer]: Added user: BooyahMagmaAroma (1152921508901814275), zone: 1000
[06-12-21 21:45:22] [ChatServer]: Asked for ignore list, but is unimplemented right now.
[06-12-21 21:45:32] [ChatServer]: A server is connecting, awaiting user list.
[06-12-21 21:45:38] [PlayerContainer]: Added user: Mindless^MHippo^MBaboon^M (1152921508901814274), zone: 1100
[06-12-21 21:45:38] [ChatServer]: Asked for ignore list, but is unimplemented right now.
[06-12-21 21:51:52] [PlayerContainer]: Removed user: 1152921508901814275
[06-12-21 21:51:55] [PlayerContainer]: Added user: BooyahMagmaAroma (1152921508901814275), zone: 1100
[06-12-21 21:51:55] [ChatServer]: Asked for ignore list, but is unimplemented right now.
[06-12-21 21:57:16] [PlayerContainer]: Removed user: 1152921508901814275
[06-12-21 21:57:24] [PlayerContainer]: Removed user: 1152921508901814274
```

Also, here is the output of  "ps -aux | grep Server".  To start the server all I execute is MasterServer as root.  As you can see from the output there are two ChatServer processes, one with sudo and one without.  Is that correct??

```
root        2211  0.2  0.9 107688 18228 pts/1    Sl   21:37   0:04 ./MasterServer
root        2214  0.0  0.2   8464  4500 pts/1    S    21:37   0:00 sudo ./ChatServer
root        2216  0.0  0.2   8464  4488 pts/1    S    21:37   0:00 sudo ./WorldServer -zone 0 -port 3001 -instance 0 -maxclients 999 -clone 0
root        2218  0.2  0.5 172696  9572 pts/1    Sl   21:37   0:03 ./ChatServer
root        2219  0.0  0.2   8460  4488 pts/1    S    21:37   0:00 sudo ./WorldServer -zone 1000 -port 3004 -instance 1 -maxclients 15 -clone 0
root        2221  0.4  1.5 267576 28528 pts/1    Sl   21:37   0:06 ./WorldServer -zone 0 -port 3001 -instance 0 -maxclients 999 -clone 0
root        2222  0.4  1.5 266592 29200 pts/1    Sl   21:37   0:06 ./WorldServer -zone 1000 -port 3004 -instance 1 -maxclients 15 -clone 0
root        2223  0.0  0.2   8460  4504 pts/1    S    21:37   0:00 sudo ./AuthServer
root        2225  0.5  0.8 179544 16388 pts/1    Sl   21:37   0:07 ./AuthServer
root        2244  0.0  0.2   8468  4460 pts/1    S    21:45   0:00 sudo ./WorldServer -zone 1100 -port 3007 -instance 2 -maxclients 31 -clone 0
root        2245  2.2  2.1 424456 40120 pts/1    Sl   21:45   0:22 ./WorldServer -zone 1100 -port 3007 -instance 2 -maxclients 31 -clone 0

```

**Comment by basedx32** [comment] 2021-12-06 22:12
> Have you confirmed an instance of ChatServer is running?

I have similar output to Landshark77. I have also tried running chatserver as sudo as well.

**Comment by Dragonisser** [comment] 2021-12-06 23:45
> > Have you confirmed an instance of ChatServer is running?
> 
> I have similar output to Landshark77. I have also tried running chatserver as sudo as well.

Can also confirm, neither local, team or friend chat works.

**Comment by makitsune** [comment] 2021-12-07 00:49
Same here, logs look similar to me.

**Comment by Mar0xy** [comment] 2021-12-07 03:15
Same issue here the only difference is the system running on oracle linux/rhel

**Comment by jelimoore** [comment] 2021-12-07 04:35
+1, chat does not work at all, also for me Chatserver dies about 30 minutes in - unrelated to chat not working. During the time chatserver is online friend requests work but when it is down friend requests stop working.

**Comment by leolion3** [comment] 2021-12-07 09:14
Same here, running on WSL.

**Comment by Pr3roxDLC** [comment] 2021-12-07 11:56
Have the same problem on Ubuntu 18.04, ps shows me everything running but chat doesnt work ingame at all

**Comment by MrPowerMac** [comment] 2021-12-07 14:02
Can also confirm this issue on native Ubuntu 20.04 (Oracle Cloud VPS).

**Comment by MichaelFedora** [comment] 2021-12-07 18:22
Chat works as a GM for me (level 2 at least), but as level 0 (civ) the filter always returns red. This also occurs for mail.

**Comment by averysumner** [comment] 2021-12-07 18:28
If you have a GM level that is greater than 1 you can chat freely without the filter. Are you sure you put the chatplus file in your res folder?

**Comment by Wincent01** [comment] 2021-12-07 18:30
A solution to this:
* Format the `build/res/chatplus_en_us.txt` to use the native file-ending for your OS `\n` for Linux/MacOS and `\r\n` for Windows.
* Delete the `build/res/chatplus_en_us.dcf`
* Restart the server to let it generate a new dcf file.

**Comment by Landshark77** [comment] 2021-12-07 19:06
> A solution to this:
> 
> * Format the `build/res/chatplus_en_us.txt` to use the native line-ending for your OS `\n` for Linux/MacOS and `\r\n` for Windows.
> * Delete the `build/res/chatplus_en_us.dcf` file
> * Restart the server to let it generate a new dcf file.

For linux you can install the dos2unix command to convert the file format.

**Comment by OwlWatcher** [comment] 2021-12-07 19:13
> 

Can confirm this works. By default, build/res/chatplus_en_us.txt seems to be formatted for Windows. Anyone using WSL or Linux will likely need to do this. To verify this, you can run `file chatplus_en_us.txt`. The output will look like the following:

**Formatted for Windows:**
chatplus_en_us.txt: ASCII text, with CRLF line terminators

**Formatted for Unix systems:**
chatplus_en_us.txt: ASCII text

**Comment by Lego6245** [comment] 2021-12-07 19:20
#38 appears to fix this for character names, would a similar fix be usable for this file?

**Comment by JoachimFlottorp** [comment] 2021-12-07 19:22
#91 Currently being reviewed, easy fix as the user should just run dos2unix. Which i have added an entry to in the README.

**Comment by MichaelFedora** [comment] 2021-12-07 19:42
> #38 appears to fix this for character names, would a similar fix be usable for this file?

I think this is the way it should go, yeah.

**Comment by basedx32** [comment] 2021-12-07 20:39
> > A solution to this:
> > 
> > * Format the `build/res/chatplus_en_us.txt` to use the native line-ending for your OS `\n` for Linux/MacOS and `\r\n` for Windows.
> > * Delete the `build/res/chatplus_en_us.dcf` file
> > * Restart the server to let it generate a new dcf file.
> 
> For linux you can install the dos2unix command to convert the file format.

Hm not sure if I did something wrong but I converted using "dos2unix chatplus_en_us.txt" and now some admin commands are working but my chat still isn't fully functional.

**Comment by averysumner** [comment] 2021-12-07 23:49
#91 was merged, solving this issue. If the issue persists feel free to reopen.

**Closed by averysumner** 2021-12-07 23:49 UTC

**Comment by Relran** [comment] 2021-12-08 19:49
when I am reaching the shop mission (at the start) my server crashes and says:

[08-12-21 21:32:10] [GameMessages]: Unable to get mission 314 for entity 1152921508901814274 to update reward in RespondToMission
[08-12-21 21:32:50] [GameMessages]: Unable to get mission 315 for entity 1152921508901814274 to update reward in RespondToMission
[08-12-21 21:32:55] [GameMessages]: Emote (356) (288300748454049803)
[08-12-21 21:32:55] [GameMessages]: Emote target found (1)
[08-12-21 21:32:58] [GameMessages]: Unable to get mission 733 for entity 1152921508901814274 to update reward in RespondToMission
[08-12-21 21:33:04] [GameMessages]: Emote (356) (0)
Fatal error 11

Anyone have an idea? help will be greatful!
