### ISSUE TITLE
BUG: Server is lagging/desyncing

### ISSUE THREAD

**Issue by WuRzA69** [DarkflameUniverse/DarkflameServer#1193] opened 2023-09-14 19:59 UTC
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

2e386d2

### Issue Description

I started a server for me and my friend after playing for 10 mins the server is lagging or desyncing with the client

a reconnct to the server fixes the problem for a short time

the shows many problems ghost enemys, loot not droping, aneble to talk to npc, ...

i tried every possible network config. Server running over the intenet with open ports, local network with closed ports and local on one maschine

### Reproduction Steps

killing enemys in avante grant until server laggs/desync

### Expected Behavior

server running with minimal/no lag or desync problems

### Environment

Windows Client

Server tested with:
Linux
Docker Linux
Docker Windows

**Comment by aronwk-aaron** [comment] 2023-09-14 20:11
try setting the `maximum_outgoing_bandwidth` to 0 in the shardconfig.ini

**Comment by EmosewaMC** [comment] 2023-09-20 01:33
Closing as this is known to fix the issue and if it doesn't it's a duplicate of the already existing docker container issue.
#1134

**Closed by EmosewaMC** 2023-09-20 01:33 UTC
Labels: bug, invalid, performance
