### ISSUE TITLE
BUG: Inventor Beehive attack doesn't account kills to the player

### ISSUE THREAD

**Issue by DerPannda** [DarkflameUniverse/DarkflameServer#232] opened 2021-12-15 00:13 UTC
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

The Inventor Improved Launcher 3 "Surprise Beehive" Attack causes the enemies to not drop loot for the player, if the attack itself kills the entity.

### Reproduction steps

1. Attack enemy with the "Surprise Beehive 2" of the Inventor Improved Launcher.
2. Wait for the enemy to die to the damage over time dealt by the attack
3. No loot will drop from the enemy despite being killed by an ability of the player.

### Expected Behavior

Instead of dropping nothing at all, the enemy is expected to drop loot as it was killed by an ability of the player.
Other abilities seem to be working fine such as Engineer Turret and Fortified Fortress or the Forcefield of the Innovator.

### Environment

Ubuntu

**Comment by Terrev** [comment] 2021-12-15 02:22
Unfortunately I don't have footage to back this up, but I'm pretty sure this was a bug during live, for what it's worth - at the very least, there was *some* problem with rank 3 beehive that made it useless, and I'm like 90% sure this was it (either that or it wasn't doing damage at all... but this sounds more familiar)

**Comment by lcdr** [comment] 2021-12-23 21:46
Update: It seems this skill uses a buff to actually deal the damage in the end, and the issue is with [BuffComponent.cpp not passing on the buff source to the skill system](https://github.com/DarkflameUniverse/DarkflameServer/blob/main/dGame/dComponents/BuffComponent.cpp#L74)  when executing the buff's behavior, and thus losing the info about the player being the one who should be credited.

**Comment by averysumner** [comment] 2022-01-31 12:13
Fixed in #306.

**Closed by averysumner** 2022-01-31 12:13 UTC
Labels: bug, priority/low
