### ISSUE TITLE
BUG: Unable to load Nexus Tower

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#882] opened 2022-12-12 03:51 UTC
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

5292f36

### Issue Description

So this is not a common issue, but it happens almost always for two players on my server. Player 1 is stuck on 55% loaded whenever trying to load Nexus Tower. He has a large amount of mods installed, so I'd keep that in mind as it could be causing issues. He also might just be cursed as for a while he couldn't load Keelhaul Canyon Racetrack. Player 2 does not have mods however, but he also gets stuck on 55% loaded for a few minutes before he is booted to the login screen. Server logs show nothing unusual, just a typical dropped connection and their client logs also show nothing unusual, so I don't really have evidence for this but it's still an issue and it impedes two players gameplay.

Here's the log for Nexus Tower anyways (disregard the user MustacheMan12, and KILO is a user who was able to load in once but the other attempts were unsuccessful) 
[WorldServer_1900_9_1670810089.log](https://github.com/DarkflameUniverse/DarkflameServer/files/10204428/WorldServer_1900_9_1670810089.log)

### Reproduction Steps

no clear way to reproduce

### Expected Behavior

nexus tower should load

### Environment

ubuntu server

**Comment by EmosewaMC** [comment] 2022-12-12 04:36
We are not going to accept bug reports from someone using a modded client.  The issue relating to that player will be ignored.

To touch on the second player, if others are able to load into a zone but one player is unable to, this is likely a misconfiguration on your end or their end, or the client is just old.

**Comment by EmosewaMC** [comment] 2022-12-12 04:39
Please also provide client logs for the player using an unmodified client

**Comment by EmosewaMC** [comment] 2022-12-19 01:04
A possible fix has been pushed. Please update and verify if this is still broken

**Comment by MustacheMan2** [comment] 2022-12-23 21:33
> A possible fix has been pushed. Please update and verify if this is still broken

The issue has not been fixed.

**Comment by EmosewaMC** [comment] 2022-12-23 22:39
Navigate to sharedconfig.ini and lower the MTU size until players are able to load in

**Comment by EmosewaMC** [comment] 2022-12-23 22:47
Unfortunately if max MTU size does not fix it there is nothing more we are able to do as the only other cause would be packet loss.

**Comment by MustacheMan2** [comment] 2022-12-29 00:03
I'm confused, am I supposed to raise or lower the MTU size? (Your latest comment contradicts the last one :P) Also, this value is not present in my sharedconfig.ini for some reason.

**Comment by EmosewaMC** [comment] 2022-12-29 00:05
> I'm confused, am I supposed to raise or lower the MTU size? (Your latest comment contradicts the last one :P) Also, this value is not present in my sharedconfig.ini for some reason.

any config.ini does not update with new values.  You'll need to copy over the new values manually to edit them

**Comment by EmosewaMC** [comment] 2023-01-23 01:12
Can you try adding `maximum_outgoing_bandwidth=80000` to the sharedconfig.ini, rebooting the server and seeing if the players still get stuck?

**Comment by MustacheMan2** [comment] 2023-05-13 22:24
> Can you try adding `maximum_outgoing_bandwidth=80000` to the sharedconfig.ini, rebooting the server and seeing if the players still get stuck?

Sorry I forgot about this entirely. I can still try this if you want but things seem good. Really hard to find a guaranteed way to fix this because it always varies on whether the affected people can load in or not. I've dealt with a total now of 4 players who've had this issue (3 of which are Italian, so maybe there's a conspiracy to be had), and lately there hasn't been any issues. Feel free to close this, although I think it'd be good to have this documented somewhere in case someone else runs into this.

**Comment by MustacheMan2** [comment] 2023-05-13 22:58
Funny how not long after I post this, one of the same users got stuck loading Crux Prime and is complaining of desync in general.

**Comment by EmosewaMC** [comment] 2023-05-13 23:06
The issues are not something we can fix.  We found an actual fix but it is unrelated to server source and is related more to networking in general.  The issue is related to networking outside of our control and no fix will be planned for this on our end.

<https://github.com/enteryournamehere/tcp_shim> this is the fix and requires the server to run it and a client setup as well.

**Closed by EmosewaMC** 2023-05-13 23:06 UTC
Labels: bug, P-needs-investigation
