### ISSUE TITLE
World Builder League Rocket

### ISSUE THREAD

**Issue by RunningPlasmaDog** [DarkflameUniverse/DarkflameServer#69] opened 2021-12-07 01:18 UTC
When you travel to a world builder league world it says "Do you want to travel to Nexus Tower?"

**Comment by averysumner** [comment] 2021-12-07 18:23
Can you post a screenshot?

**Comment by averysumner** [comment] 2021-12-07 18:33
I’m able to reproduce, it’s not a major issue though so don’t expect a fix very soon.

**Comment by Xiphoseer** [comment] 2022-02-05 15:24
This inheritance is probably the problem: https://github.com/DarkflameUniverse/DarkflameServer/blob/a9860388b2b34d4a52c63c673d0e4a94ec089ebc/dScripts/SbLupTeleport.h#L7

**Comment by aronwk-aaron** [comment] 2022-05-02 23:44
After looking into this some, this can be fixed one of two ways.

1) properly implement it as it was in live:
see https://youtu.be/K2s7U9_OMDU?t=872
Which from what I can tell is using the same `MultiZoneNavigator` that is used by the property launghpads.
This would make it more live accurate

Or 2) just override the `BaseChoiceBoxRespond` to display the Zones name and make it display something relevant.
Since there is no `UI_TRAVEL_TO_MOONBASE` or like strings in local for LUP worlds, it would just be the name or descriptions in the confirmation box of the ChoiceBox

**Closed** 2022-05-06 18:54 UTC
Labels: bug, P-low, A-scripts
