### ISSUE TITLE
BUG: Dying in Avant Gardens Survival causes you to lose coins

### ISSUE THREAD

**Issue by Marcono1234** [DarkflameUniverse/DarkflameServer#425] opened 2022-01-30 03:59 UTC
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Version: 344af924feb643801d70c8c2f9bac765127bb62a

When dying in Avant Gardens Survival, you lose coins.

### Reproduction steps

1. Start an Avant Gardens Survival game (solo)
2. Die

### Expected Behavior

You should not lose any coins.

### Environment

WSL 2, Docker Compose setup

**Comment by EmosewaMC** [comment] 2022-01-30 08:45
Dupe of #174

**Closed** 2022-01-30 17:36 UTC
Labels: bug, triage
