### ISSUE TITLE
Gnarled Forest Apes don't attack properly

### ISSUE THREAD

**Issue by MustacheMan2** [DarkflameUniverse/DarkflameServer#198] opened 2021-12-12 17:50 UTC
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Apes in Gnarled Forest have two issues.

1. Not all of their boulders are visible
2. They will start a ground pound around 3 times at the same time so they will all come in a large burst. They will also throw boulders during the ground pound. Very challenging and fun at times, but not live accurate.

https://user-images.githubusercontent.com/48499798/145723554-54bc33e5-49b0-4872-bf52-953af4a6aa2e.mp4

### Reproduction steps

Attack an ape in Gnarled Forest

### Expected Behavior

all boulders should be visible. Attacks should not merge with each other.

### Environment

Ubuntu server

**Comment by Wincent01** [comment] 2021-12-12 18:38
I worked on mitigating this issue a lot. It has something to do with the state that the verify behavior's serialization is in; it's mostly guesswork.
https://github.com/DarkflameUniverse/DarkflameServer/blob/d7294bda55bda53768eddfb435bc5b5d31941613/dGame/dBehaviors/VerifyBehavior.cpp#L10-L61

**Comment by MrPowerMac** [comment] 2021-12-14 02:39
I've noticed this same behavior occurring with apes on Crux Prime (both Stromling Ape Invaders and Roo Morgg).

**Comment by fyreaken** [comment] 2021-12-14 06:43
This doesn't seem to affect Kinga Hurl in Battle for Nimbus Station, the ape reacts just like they did on live.

**Comment by EmosewaMC** [comment] 2022-02-06 11:53
I have deduced down the root cause of this behavior issue.  It has to do with the stun immunity applied to the apes.  The BoNS ape before the patch that fixes it to be stun immune now forces the ape to act exactly like the ones on Gnarled Forest and Crux Prime.  A fix should be in the works soon but no promises.

**Comment by FutronBob** [comment] 2022-03-07 07:17
This video here is the best footage of the original game I could find that demonstrates how the Apes should be timing their attacks.  Starts at 20:12 - https://youtu.be/HAaknVJU3Ew?t=1212

I can confirm that this was how Kinga Hurl was behaving on Darkflame before the change Emosewa mentioned above.

**Comment by EmosewaMC** [comment] 2022-03-31 09:54
Fixed by #475

**Closed by EmosewaMC** 2022-03-31 09:54 UTC
Labels: bug, P-low, A-game, B-behaviors
