### ISSUE TITLE
BUG: Stuck in Venture Explorer and kick to login when Rocket building

### ISSUE THREAD

**Issue by Dopes88** [DarkflameUniverse/DarkflameServer#1322] opened 2023-11-26 15:26 UTC
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

fd20baaf

### Issue Description

When building a Rocket or trying to travel to Avant Gardens the Client get kicked off and pushed back to the main Menu.

AuthServer Logs:

`[26-11-23 16:12:44 AuthServer.cpp:54] Starting Auth server...
[26-11-23 16:12:44 AuthServer.cpp:55] Version: 1.1
[26-11-23 16:12:44 AuthServer.cpp:56] Compiled on: Thu Nov 23 22:16:47 2023
[26-11-23 16:12:44 dServer.cpp:68] Server is listening on 45.82.122.110:1001 with encryption: 1
[26-11-23 16:12:44 dServer.cpp:117] Established connection to master, zone (0), instance (0)
[26-11-23 16:13:00 AuthPackets.cpp:54] Received client version: 171022
[26-11-23 16:13:01 AuthPackets.cpp:233] Set sessionKey: 1741319249 for user Kush
[26-11-23 16:15:18 MySQLDatabase.cpp:57] Destroying MySQL connection from AuthServer!
`

ChatServer Logs:

`[26-11-23 16:12:44 ChatServer.cpp:61] Starting Chat server...
[26-11-23 16:12:44 ChatServer.cpp:62] Version: 1.1
[26-11-23 16:12:44 ChatServer.cpp:63] Compiled on: Thu Nov 23 22:16:47 2023
[26-11-23 16:12:44 dServer.cpp:68] Server is listening on 45.82.122.110:2005 with encryption: 1
[26-11-23 16:12:44 dServer.cpp:117] Established connection to master, zone (0), instance (0)
[26-11-23 16:12:45 ChatServer.cpp:195] A server is connecting, awaiting user list.
[26-11-23 16:12:45 ChatServer.cpp:195] A server is connecting, awaiting user list.
[26-11-23 16:13:10 PlayerContainer.cpp:49] Added user: Kush (1152921508901814274), zone: 1000
[26-11-23 16:13:10 ChatServer.cpp:237] Asked for ignore list, but is unimplemented right now.
[26-11-23 16:15:08 PlayerContainer.cpp:85] Removed user: 1152921508901814274
[26-11-23 16:15:18 MySQLDatabase.cpp:57] Destroying MySQL connection from ChatServer!`

MasterServer Logs:

`[26-11-23 16:12:44 MasterServer.cpp:126] Using net version 171022
[26-11-23 16:12:44 MasterServer.cpp:128] Starting Master server...
[26-11-23 16:12:44 MasterServer.cpp:129] Version: 1.1
[26-11-23 16:12:44 MasterServer.cpp:130] Compiled on: Thu Nov 23 22:16:47 2023
[26-11-23 16:12:44 MigrationRunner.cpp:59] Server database is up to date.
[26-11-23 16:12:44 MigrationRunner.cpp:132] CDServer database is up to date.
[26-11-23 16:12:44 dServer.cpp:68] Server is listening on 45.82.122.110:2000 with encryption: 0
[26-11-23 16:12:44 InstanceManager.cpp:31] Searching for an instance for mapID 0/0
[26-11-23 16:12:44 InstanceManager.cpp:91] Created new instance: 0/0/0 with min/max 999/999
[26-11-23 16:12:44 InstanceManager.cpp:31] Searching for an instance for mapID 1000/0
[26-11-23 16:12:44 InstanceManager.cpp:91] Created new instance: 1000/1/0 with min/max 10/15
[26-11-23 16:12:44 MasterServer.cpp:580] Received server info, instance: 0 port: 2005
[26-11-23 16:12:44 MasterServer.cpp:580] Received server info, instance: 0 port: 1001
[26-11-23 16:12:45 MasterServer.cpp:580] Received server info, instance: 0 port: 3000
[26-11-23 16:12:45 MasterServer.cpp:580] Received server info, instance: 1 port: 3003
[26-11-23 16:12:48 MasterServer.cpp:741] Got world ready 1000 1
[26-11-23 16:12:48 MasterServer.cpp:750] Ready zone 1000
[26-11-23 16:12:48 MasterServer.cpp:741] Got world ready 0 0
[26-11-23 16:12:48 MasterServer.cpp:750] Ready zone 0
[26-11-23 16:13:00 MasterServer.cpp:489] Received zone transfer req
[26-11-23 16:13:00 InstanceManager.cpp:31] Searching for an instance for mapID 0/0
[26-11-23 16:13:00 MasterServer.cpp:508] Instance: 0/0/0 -> 1
[26-11-23 16:13:00 MasterServer.cpp:508] Instance: 1000/0/1 -> 0
[26-11-23 16:13:00 MasterServer.cpp:519] Responding to transfer request 1 for zone 0 0
[26-11-23 16:13:00 InstanceManager.cpp:210] Sent affirmation request 1 to 0/0
[26-11-23 16:13:01 MasterServer.cpp:779] Got affirmation of transfer 1
[26-11-23 16:13:01 MasterServer.cpp:787] Affirmation complete 1
[26-11-23 16:13:01 MasterServer.cpp:612] Got sessionKey 1741319249 for user Kush
[26-11-23 16:13:08 MasterServer.cpp:489] Received zone transfer req
[26-11-23 16:13:08 InstanceManager.cpp:31] Searching for an instance for mapID 1000/0
[26-11-23 16:13:08 MasterServer.cpp:508] Instance: 0/0/0 -> 0
[26-11-23 16:13:08 MasterServer.cpp:508] Instance: 1000/0/1 -> 1
[26-11-23 16:13:08 MasterServer.cpp:519] Responding to transfer request 1 for zone 1000 0
[26-11-23 16:13:08 InstanceManager.cpp:210] Sent affirmation request 1 to 1000/0
[26-11-23 16:13:08 MasterServer.cpp:779] Got affirmation of transfer 1
[26-11-23 16:13:08 MasterServer.cpp:787] Affirmation complete 1
[26-11-23 16:15:18 MasterServer.cpp:872] Triggered master shutdown
[26-11-23 16:15:18 MasterServer.cpp:878] Saved ObjectIDTracker to DB
[26-11-23 16:15:18 MasterServer.cpp:892] Attempting to shutdown instances, max 60 seconds...
[26-11-23 16:15:18 MasterServer.cpp:801] Got shutdown response from zone 1000 clone 0 instance 1 port 3003
[26-11-23 16:15:18 MasterServer.cpp:801] Got shutdown response from zone 0 clone 0 instance 0 port 3000
[26-11-23 16:15:18 MasterServer.cpp:429] A server has disconnected
[26-11-23 16:15:18 MasterServer.cpp:436] Actually disconnected from zone 1000 clone 0 instance 1 port 3003
[26-11-23 16:15:18 MasterServer.cpp:429] A server has disconnected
[26-11-23 16:15:18 MasterServer.cpp:436] Actually disconnected from zone 0 clone 0 instance 0 port 3000
[26-11-23 16:15:18 MasterServer.cpp:429] A server has disconnected
[26-11-23 16:15:18 MasterServer.cpp:839] Currently shutting down.  Auth will not be restarted.
[26-11-23 16:15:18 MasterServer.cpp:429] A server has disconnected
[26-11-23 16:15:18 MasterServer.cpp:820] Currently shutting down.  Chat will not be restarted.
[26-11-23 16:15:18 MasterServer.cpp:920] Finished shutting down MasterServer!
[26-11-23 16:15:18 MySQLDatabase.cpp:57] Destroying MySQL connection from MasterServer!
`

WorldServer 0 Logs:

`[26-11-23 16:12:44 WorldServer.cpp:152] Starting World server...
[26-11-23 16:12:44 WorldServer.cpp:153] Version: 1.1
[26-11-23 16:12:44 WorldServer.cpp:154] Compiled on: Thu Nov 23 22:16:47 2023
[26-11-23 16:12:45 dServer.cpp:68] Server is listening on 127.0.0.1:3000 with encryption: 1
[26-11-23 16:12:45 dServer.cpp:117] Established connection to master, zone (0), instance (0)
[26-11-23 16:12:45 WorldServer.cpp:545] Established connection to chat, zone(0), instance (0)
[26-11-23 16:12:48 WorldServer.cpp:505] Finished loading world with zone (0), ready up!
[26-11-23 16:13:00 WorldServer.cpp:810] Got affirmation request of transfer 1
[26-11-23 16:13:01 AuthPackets.cpp:54] Received client version: 171022
[26-11-23 16:13:01 WorldServer.cpp:765] User Kush authenticated with correct key.
[26-11-23 16:13:01 Character.cpp:85] Loaded xmlData for character Kush (2)!
[26-11-23 16:13:08 UserManager.cpp:451] Transferring Kush to Zone 1000 (Instance 1 | Clone 0 | Mythran Shift: false) with IP 45.82.122.110 and Port 3003
[26-11-23 16:13:08 UserManager.cpp:153] Deleted user 1
[26-11-23 16:15:18 WorldServer.cpp:1293] Zone (0) instance (0) shutting down outside of main loop!
[26-11-23 16:15:18 WorldServer.cpp:1251] Saving map 0 instance 0
[26-11-23 16:15:18 WorldServer.cpp:1276] ALL DATA HAS BEEN SAVED FOR ZONE 0 INSTANCE 0!
[26-11-23 16:15:18 WorldServer.cpp:1299] Shutdown complete, zone (0), instance (0)
[26-11-23 16:15:18 MySQLDatabase.cpp:57] Destroying MySQL connection from WorldServer!
`

WorldServer 1000 Logs:

`[26-11-23 16:12:44 WorldServer.cpp:152] Starting World server...
[26-11-23 16:12:44 WorldServer.cpp:153] Version: 1.1
[26-11-23 16:12:44 WorldServer.cpp:154] Compiled on: Thu Nov 23 22:16:47 2023
[26-11-23 16:12:45 dServer.cpp:70] Server is listening on 127.0.0.1:3003 with encryption: 1, running zone 1000 / 1
[26-11-23 16:12:45 dNavMesh.cpp:24] Navmesh loaded successfully!
[26-11-23 16:12:45 dpWorld.cpp:26] Physics world initialized!
[26-11-23 16:12:45 dZoneManager.cpp:21] Preparing zone: 1000/1/0
[26-11-23 16:12:45 dZoneManager.cpp:49] Creating zone control object 2365
[26-11-23 16:12:45 dZoneManager.cpp:250] Loading WorldConfig into memory
[26-11-23 16:12:45 dZoneManager.cpp:320] Loaded WorldConfig into memory
[26-11-23 16:12:45 dZoneManager.cpp:69] Zone prepared in: 98 ms
[26-11-23 16:12:45 dServer.cpp:117] Established connection to master, zone (1000), instance (1)
[26-11-23 16:12:45 WorldServer.cpp:545] Established connection to chat, zone(1000), instance (1)
[26-11-23 16:12:48 WorldServer.cpp:505] Finished loading world with zone (1000), ready up!
[26-11-23 16:13:08 WorldServer.cpp:810] Got affirmation request of transfer 1
[26-11-23 16:13:08 AuthPackets.cpp:54] Received client version: 171022
[26-11-23 16:13:08 WorldServer.cpp:765] User Kush authenticated with correct key.
[26-11-23 16:13:08 Character.cpp:85] Loaded xmlData for character Kush (2)!
[26-11-23 16:13:08 User.cpp:41] Loaded 2 as it is the last used char
[26-11-23 16:13:10 WorldServer.cpp:1010] Received level load complete from user.
[26-11-23 16:13:10 ControllablePhysicsComponent.cpp:55] Using patch to load minifig physics
[26-11-23 16:13:10 WorldPackets.cpp:197] Sent CreateCharacter for ID: 1152921508901814274
[26-11-23 16:13:12 GameMessageHandler.cpp:172] Player Kush (1152921508901814274) loaded.
[26-11-23 16:14:43 Behavior.cpp:432] Failed to load behavior with id (0)!
[26-11-23 16:15:03 BuildBorderComponent.cpp:44] Starting with 288300748454049503
[26-11-23 16:15:03 GameMessages.cpp:2278] Sending build mode confirm (9980): (1) (-1) (0) (1) (1152921508901814274)
[26-11-23 16:15:05 GameMessages.cpp:5515] Set build mode to (1) for (1152921508901814274)
[26-11-23 16:15:06 GameMessages.cpp:5515] Set build mode to (1) for (1152921508901814274)
[26-11-23 16:15:06 GameMessageHandler.cpp:52] Failed to find associated entity (288230376151711916), aborting GM (7C)!
[26-11-23 16:15:06 GameMessageHandler.cpp:52] Failed to find associated entity (288230376151711917), aborting GM (7C)!
[26-11-23 16:15:07 CharacterComponent.cpp:375] Time since last save: 117
[26-11-23 16:15:08 Character.cpp:324] 2:Kush Saved character to Database in: 0.003861s
[26-11-23 16:15:08 WorldServer.cpp:694] Deleting player 1152921508901814274
[26-11-23 16:15:08 Player.cpp:263] Deleted player
[26-11-23 16:15:08 CharacterComponent.cpp:375] Time since last save: 1
[26-11-23 16:15:08 Character.cpp:324] 2:Kush Saved character to Database in: 0.002131s
[26-11-23 16:15:08 UserManager.cpp:153] Deleted user 1
[26-11-23 16:15:18 WorldServer.cpp:1293] Zone (1000) instance (1) shutting down outside of main loop!
[26-11-23 16:15:18 WorldServer.cpp:1251] Saving map 1000 instance 1
[26-11-23 16:15:18 WorldServer.cpp:1276] ALL DATA HAS BEEN SAVED FOR ZONE 1000 INSTANCE 1!
[26-11-23 16:15:18 WorldServer.cpp:1299] Shutdown complete, zone (1000), instance (1)
[26-11-23 16:15:18 MySQLDatabase.cpp:57] Destroying MySQL connection from WorldServer!
[26-11-23 16:15:18 Zone.cpp:32] Destroying zone 1000
`

Server Console Output:

`[26-11-23 16:21:08 MasterServer.cpp:126] Using net version 171022
[26-11-23 16:21:08 MasterServer.cpp:128] Starting Master server...
[26-11-23 16:21:08 MasterServer.cpp:129] Version: 1.1
[26-11-23 16:21:08 MasterServer.cpp:130] Compiled on: Thu Nov 23 22:16:47 2023
[26-11-23 16:21:08 MigrationRunner.cpp:59] Server database is up to date.
[26-11-23 16:21:08 MigrationRunner.cpp:132] CDServer database is up to date.
[26-11-23 16:21:08 dServer.cpp:68] Server is listening on 45.82.122.110:2000 with encryption: 0
[26-11-23 16:21:08 InstanceManager.cpp:31] Searching for an instance for mapID 0/0
[26-11-23 16:21:08 InstanceManager.cpp:91] Created new instance: 0/0/0 with min/max 999/999
[26-11-23 16:21:08 InstanceManager.cpp:31] Searching for an instance for mapID 1000/0
[26-11-23 16:21:08 InstanceManager.cpp:91] Created new instance: 1000/1/0 with min/max 10/15
[26-11-23 16:21:08 ChatServer.cpp:61] Starting Chat server...
[26-11-23 16:21:08 ChatServer.cpp:62] Version: 1.1
[26-11-23 16:21:08 ChatServer.cpp:63] Compiled on: Thu Nov 23 22:16:47 2023
[26-11-23 16:21:08 WorldServer.cpp:152] Starting World server...
[26-11-23 16:21:08 WorldServer.cpp:153] Version: 1.1
[26-11-23 16:21:08 WorldServer.cpp:154] Compiled on: Thu Nov 23 22:16:47 2023
[26-11-23 16:21:08 dServer.cpp:68] Server is listening on 45.82.122.110:2005 with encryption: 1
[26-11-23 16:21:08 WorldServer.cpp:152] Starting World server...
[26-11-23 16:21:08 WorldServer.cpp:153] Version: 1.1
[26-11-23 16:21:08 WorldServer.cpp:154] Compiled on: Thu Nov 23 22:16:47 2023
[26-11-23 16:21:08 AuthServer.cpp:54] Starting Auth server...
[26-11-23 16:21:08 AuthServer.cpp:55] Version: 1.1
[26-11-23 16:21:08 AuthServer.cpp:56] Compiled on: Thu Nov 23 22:16:47 2023
[26-11-23 16:21:08 dServer.cpp:68] Server is listening on 45.82.122.110:1001 with encryption: 1
[26-11-23 16:21:08 dServer.cpp:117] Established connection to master, zone (0), instance (0)
[26-11-23 16:21:08 dServer.cpp:117] Established connection to master, zone (0), instance (0)
[26-11-23 16:21:08 MasterServer.cpp:580] Received server info, instance: 0 port: 2005
[26-11-23 16:21:08 MasterServer.cpp:580] Received server info, instance: 0 port: 1001
[26-11-23 16:21:09 dServer.cpp:70] Server is listening on 127.0.0.1:3003 with encryption: 1, running zone 1000 / 1
[26-11-23 16:21:09 dServer.cpp:68] Server is listening on 127.0.0.1:3000 with encryption: 1
[26-11-23 16:21:09 dNavMesh.cpp:24] Navmesh loaded successfully!
[26-11-23 16:21:09 dpWorld.cpp:26] Physics world initialized!
[26-11-23 16:21:09 dZoneManager.cpp:21] Preparing zone: 1000/1/0
[26-11-23 16:21:09 dZoneManager.cpp:49] Creating zone control object 2365
[26-11-23 16:21:09 dServer.cpp:117] Established connection to master, zone (0), instance (0)
[26-11-23 16:21:09 WorldServer.cpp:545] Established connection to chat, zone(0), instance (0)
[26-11-23 16:21:09 dZoneManager.cpp:250] Loading WorldConfig into memory
[26-11-23 16:21:09 dZoneManager.cpp:320] Loaded WorldConfig into memory
[26-11-23 16:21:09 dZoneManager.cpp:69] Zone prepared in: 115 ms
[26-11-23 16:21:09 ChatServer.cpp:195] A server is connecting, awaiting user list.
[26-11-23 16:21:09 ChatServer.cpp:195] A server is connecting, awaiting user list.
[26-11-23 16:21:09 MasterServer.cpp:580] Received server info, instance: 0 port: 3000
[26-11-23 16:21:09 dServer.cpp:117] Established connection to master, zone (1000), instance (1)
[26-11-23 16:21:09 WorldServer.cpp:545] Established connection to chat, zone(1000), instance (1)
[26-11-23 16:21:09 MasterServer.cpp:580] Received server info, instance: 1 port: 3003
[26-11-23 16:21:12 WorldServer.cpp:505] Finished loading world with zone (1000), ready up!
[26-11-23 16:21:12 MasterServer.cpp:741] Got world ready 1000 1
[26-11-23 16:21:12 MasterServer.cpp:750] Ready zone 1000
[26-11-23 16:21:12 WorldServer.cpp:505] Finished loading world with zone (0), ready up!
[26-11-23 16:21:12 MasterServer.cpp:741] Got world ready 0 0
[26-11-23 16:21:12 MasterServer.cpp:750] Ready zone 0
[26-11-23 16:22:49 AuthPackets.cpp:54] Received client version: 171022
[26-11-23 16:22:49 MasterServer.cpp:489] Received zone transfer req
[26-11-23 16:22:49 InstanceManager.cpp:31] Searching for an instance for mapID 0/0
[26-11-23 16:22:49 MasterServer.cpp:508] Instance: 0/0/0 -> 1
[26-11-23 16:22:49 MasterServer.cpp:508] Instance: 1000/0/1 -> 0
[26-11-23 16:22:49 MasterServer.cpp:519] Responding to transfer request 1 for zone 0 0
[26-11-23 16:22:49 InstanceManager.cpp:210] Sent affirmation request 1 to 0/0
[26-11-23 16:22:49 WorldServer.cpp:810] Got affirmation request of transfer 1
[26-11-23 16:22:49 MasterServer.cpp:779] Got affirmation of transfer 1
[26-11-23 16:22:49 MasterServer.cpp:787] Affirmation complete 1
[26-11-23 16:22:49 AuthPackets.cpp:233] Set sessionKey: -187085909 for user Kush
[26-11-23 16:22:49 MasterServer.cpp:612] Got sessionKey -187085909 for user Kush
[26-11-23 16:22:49 AuthPackets.cpp:54] Received client version: 171022
[26-11-23 16:22:50 WorldServer.cpp:765] User Kush authenticated with correct key.
[26-11-23 16:22:50 Character.cpp:85] Loaded xmlData for character Kush (2)!
[26-11-23 16:22:50 GameMessageHandler.cpp:52] Failed to find associated entity (1152921508901814274), aborting GM (7C)!
[26-11-23 16:22:55 MasterServer.cpp:489] Received zone transfer req
[26-11-23 16:22:55 InstanceManager.cpp:31] Searching for an instance for mapID 1000/0
[26-11-23 16:22:55 MasterServer.cpp:508] Instance: 0/0/0 -> 0
[26-11-23 16:22:55 MasterServer.cpp:508] Instance: 1000/0/1 -> 1
[26-11-23 16:22:55 MasterServer.cpp:519] Responding to transfer request 1 for zone 1000 0
[26-11-23 16:22:55 InstanceManager.cpp:210] Sent affirmation request 1 to 1000/0
[26-11-23 16:22:55 WorldServer.cpp:810] Got affirmation request of transfer 1
[26-11-23 16:22:55 MasterServer.cpp:779] Got affirmation of transfer 1
[26-11-23 16:22:55 MasterServer.cpp:787] Affirmation complete 1
[26-11-23 16:22:55 UserManager.cpp:451] Transferring Kush to Zone 1000 (Instance 1 | Clone 0 | Mythran Shift: false) with IP 45.82.122.110 and Port 3003
[26-11-23 16:22:55 UserManager.cpp:153] Deleted user 1
[26-11-23 16:22:55 AuthPackets.cpp:54] Received client version: 171022
[26-11-23 16:22:55 WorldServer.cpp:765] User Kush authenticated with correct key.
[26-11-23 16:22:55 Character.cpp:85] Loaded xmlData for character Kush (2)!
[26-11-23 16:22:55 User.cpp:41] Loaded 2 as it is the last used char
[26-11-23 16:22:58 WorldServer.cpp:1010] Received level load complete from user.
[26-11-23 16:22:58 ControllablePhysicsComponent.cpp:55] Using patch to load minifig physics
[26-11-23 16:22:58 WorldPackets.cpp:197] Sent CreateCharacter for ID: 1152921508901814274
[26-11-23 16:22:58 PlayerContainer.cpp:49] Added user: Kush (1152921508901814274), zone: 1000
[26-11-23 16:22:58 ChatServer.cpp:237] Asked for ignore list, but is unimplemented right now.
[26-11-23 16:23:00 GameMessageHandler.cpp:172] Player Kush (1152921508901814274) loaded.
[26-11-23 16:23:08 CharacterComponent.cpp:375] Time since last save: 10
[26-11-23 16:23:08 Character.cpp:324] 2:Kush Saved character to Database in: 0.003029s
[26-11-23 16:23:08 MasterServer.cpp:765] Prepping zone 1100
[26-11-23 16:23:08 InstanceManager.cpp:31] Searching for an instance for mapID 1100/0
[26-11-23 16:23:08 InstanceManager.cpp:91] Created new instance: 1100/2/0 with min/max 22/31
[26-11-23 16:23:08 WorldServer.cpp:152] Starting World server...
[26-11-23 16:23:08 WorldServer.cpp:153] Version: 1.1
[26-11-23 16:23:08 WorldServer.cpp:154] Compiled on: Thu Nov 23 22:16:47 2023
[26-11-23 16:23:08 dServer.cpp:70] Server is listening on 127.0.0.1:3006 with encryption: 1, running zone 1100 / 2
[26-11-23 16:23:08 dNavMesh.cpp:24] Navmesh loaded successfully!
[26-11-23 16:23:08 dpWorld.cpp:26] Physics world initialized!
[26-11-23 16:23:08 dZoneManager.cpp:21] Preparing zone: 1100/2/0
[26-11-23 16:23:08 dZoneManager.cpp:49] Creating zone control object 2365
[26-11-23 16:23:08 ChatServer.cpp:195] A server is connecting, awaiting user list.
[26-11-23 16:23:08 dZoneManager.cpp:250] Loading WorldConfig into memory
[26-11-23 16:23:08 dZoneManager.cpp:320] Loaded WorldConfig into memory
[26-11-23 16:23:08 dZoneManager.cpp:69] Zone prepared in: 331 ms
[26-11-23 16:23:09 Behavior.cpp:432] Failed to load behavior with id (0)!
[26-11-23 16:23:10 CharacterComponent.cpp:375] Time since last save: 2
[26-11-23 16:23:10 Character.cpp:324] 2:Kush Saved character to Database in: 0.003921s
[26-11-23 16:23:10 WorldServer.cpp:694] Deleting player 1152921508901814274
[26-11-23 16:23:10 PlayerContainer.cpp:85] Removed user: 1152921508901814274
[26-11-23 16:23:10 Player.cpp:263] Deleted player
[26-11-23 16:23:10 CharacterComponent.cpp:375] Time since last save: 0
[26-11-23 16:23:10 Character.cpp:324] 2:Kush Saved character to Database in: 0.001162s
[26-11-23 16:23:10 UserManager.cpp:153] Deleted user 1
[26-11-23 16:23:12 BouncerComponent.cpp:90] Failed to load pet bouncer
[26-11-23 16:23:15 dServer.cpp:117] Established connection to master, zone (1100), instance (2)
[26-11-23 16:23:15 WorldServer.cpp:545] Established connection to chat, zone(1100), instance (2)
[26-11-23 16:23:15 BouncerComponent.cpp:84] Loaded pet bouncer
[26-11-23 16:23:15 MasterServer.cpp:580] Received server info, instance: 2 port: 3006
[26-11-23 16:23:15 WorldServer.cpp:505] Finished loading world with zone (1100), ready up!
[26-11-23 16:23:15 MasterServer.cpp:741] Got world ready 1100 2
[26-11-23 16:23:15 MasterServer.cpp:750] Ready zone 1100
`

Client: 0d862f71eedcadc4494c4358261669721b40b2131101cbd6ef476c5a6ec6775b unpacked

Everything has been build like in the Readme

Thank you for help!

### Reproduction Steps

1. Finish all Missions and achievements
2. Build a Rocket or try to travel to Avant Gardens

### Expected Behavior

- Travel to Avant Gardens
- Not crash
- Not get back to the Main Menu

### Environment

Rootserver Linux Debian 12 (Bookworm)
1 Core
1 GB Ram
10 GB SSD

**Comment by EmosewaMC** [comment] 2023-11-26 21:54
Have you followed the directions for client setup and set the ugcuse3dservices value to 0?  Aside from that getting kicked from traveling is a duplicate issue of a known wontfix issue due to network configuration.

**Comment by EmosewaMC** [comment] 2023-11-26 21:56
There is also no crash.  If you get getting kicked to login after building a rocket, this tells me you did not fully read through and alter your boot.cfg correctly.

**Comment by EmosewaMC** [comment] 2023-11-26 22:03
Duplicate of #1277 for the rocket issue, duplicate of the unable to load issues already reported.

**Comment by aronwk-aaron** [comment] 2024-01-05 13:49
closing as this is a user configuration isse

**Closed by aronwk-aaron** 2024-01-05 13:49 UTC
Labels: bug, P-misconfiguration
