### ISSUE TITLE
BUG: "Study the Maelstrom" Mission from Master Fong Not Completable

### ISSUE THREAD

**Issue by OfficialLahusa** [DarkflameUniverse/DarkflameServer#296] opened 2021-12-22 19:45 UTC
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Master Fong Shader's "Study the Maelstrom" mission, which leads to Wisp Lee. doesn't complete when talking to Wisp Lee. Instead, the mission popup for "Sample for Science" opens, which upon accepting, doesn't add the quest (possibly related to #144). Wisp Lee keeps glowing, and the quest popup doesn't disappear. Neither of the involved quests can be completed.
![grafik](https://user-images.githubusercontent.com/34841946/147146617-9152c3ef-09c6-459e-9351-f4a75bcfb6a7.png)
![grafik](https://user-images.githubusercontent.com/34841946/147146654-d0e584aa-2da9-4ed4-8283-69e0888eeeee.png)

### Reproduction steps

1. Talk to Master Fong Shader and pick up "Study the Maelstrom"
2. Have every other Avant Garden related mission completed (Not sure if this influences the behavior)
3. Talk to Wisp Lee

### Expected Behavior

"Study the Maelstrom" completes

### Environment

Ubuntu

**Comment by OfficialLahusa** [comment] 2021-12-22 19:48
Additional Context:
While the "Sample for Science" mission does not appear as a quest in the UI, the Maelstrom thingies still appear on the map:
![grafik](https://user-images.githubusercontent.com/34841946/147147296-2b659fec-f5bc-4ade-8068-27790dd7c263.png)

**Comment by metric-ambient** [comment] 2021-12-22 20:25
Also have had this issue. Had to spawn the maelstrom cube manually to complete it but would like a permanent solution for non admin players on my server.

**Comment by averysumner** [comment] 2021-12-22 21:43
Is this a duplicate of #255?

**Comment by OfficialLahusa** [comment] 2021-12-22 22:24
> Is this a duplicate of #255?
In contrast to #255 this bug includes the quest missing at the top of the screen and the maelstrom vacuum missing

**Comment by CACGaming** [comment] 2021-12-23 18:57
I had this same problem but got it to work by talking to Hu Where, getting the repeatable mission, and then talking to Wisp Lee, at which point talking to him brought up the menu to select the mission you wanted to talk about.

**Comment by OfficialLahusa** [comment] 2021-12-23 20:21
I can confirm that accepting the daily mission from Hu WHere fixes this issue

**Comment by OfficialLahusa** [comment] 2021-12-23 20:24
Now the other problem remains: Not receiving the Maelstrom cube after handing Wisp Lee the Maelstrom pieces

**Comment by MickVermeulen** [comment] 2021-12-28 09:10
This mission has been a major pain in the past as it's a one off config in the entire game (surprisingly). Will assign medium prio as it now seems to affect more than just the related daily.

**Comment by HIMHIM2204** [comment] 2021-12-31 10:21
I might want to point out the potential cause of the mentioned issue, I do notice that the reply after talking to wisp lee seems to be a mixed result of separated dialogue, suggesting the intended outcome to be {first part of the conversiation}-->talk to wisp lee (complete)--->accept mission on getting Maelstrom cube

**Comment by Quarko13** [comment] 2022-01-02 20:50
I think this is an issue with getting the item rewards for the dailies a second time, because you also don't get the item rewards of other daily missions like the Gem Packs or Armor Packs from Epsilon/Beckheart. Only the Coins and U-Score, but not the items.

**Comment by EmosewaMC** [comment] 2022-01-18 11:40
I've experienced this behavior at last and have a vague idea of how to reproduce it.  To fix it you need to get the mission from Hu Where what is a pre-req for this mission.  Will investigate further down the line

**Comment by MustacheMan2** [comment] 2023-01-26 16:16
I am only now experiencing this issue after going through many successful playthroughs, however what makes this one different is that I did Hu Where's daily recently, which I hadn't tried on other characters.

**Comment by EmosewaMC** [comment] 2023-01-27 02:39
triaging to low as a workaround is known and this does not affect gameplay.

**Closed** 2023-10-09 13:11 UTC
Labels: bug, P-low
