### ISSUE TITLE
BUG: Enemies become invincible from Samurai buff

### ISSUE THREAD

**Issue by IAmVolvic** [DarkflameUniverse/DarkflameServer#328] opened 2021-12-31 00:27 UTC
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

When having a full-set Samurai gear no matter the level, the buff " When you reach 0 Armor,  nearby characters will be shielded from 15 damage for a short time " Issue is it doesn't wear off so the enemies become invincible. 

This is an issue when you're just playing the game in general and you can no longer kill anything near you

### Reproduction steps

Equip a set of 4 piece samurai set lose some armor next to an enemy and wait till the buff wears off and then you can no longer kill the enemy

### Expected Behavior

When buff wears off the enemy/enemies buff should continue to take damage ( or how live did it ) not 100% sure

### Environment

Local Server 

Distributor ID: Ubuntu
Description: Ubuntu 20.04.3 LTS
Release: 20.04
Codename: focal

Mysql: Ver 8.0.27-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))

Ram: 128

Supermicro 8-Bay 2xE5-2670v3

**Comment by heatraydeathgun** [comment] 2021-12-31 13:28
We've also been seeing this. Nearby enemies receive permanent (so far in testing) invincibility from the Samurai 4-item passive triggering, while intended function is to grant only surrounding players protection from X amount of damage for a short time after reaching 0 armor.

**Comment by metric-ambient** [comment] 2021-12-31 20:32
My friend experience this with the Samurai gear as well.

**Comment by MichaelFedora** [comment] 2022-01-04 15:12
duplicate of https://github.com/DarkflameUniverse/DarkflameServer/issues/211 I believe

**Comment by averysumner** [comment] 2022-01-05 08:36
Duplicate of #211.

**Closed by averysumner** 2022-01-05 08:36 UTC
Labels: bug, triage
