### ISSUE TITLE
BUG: Mr Ree Shady Vendor Camera

### ISSUE THREAD

**Issue by leolion3** [DarkflameUniverse/DarkflameServer#179] opened 2021-12-11 12:52 UTC
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

The camera being sold by Mr. Ree in Paradox in Nexus Tower is missing its name and displayed as "Objects_16253_name"

### Reproduction steps

Go to Nexus Tower into Paradox and open Mr. Ree's shop.

### Expected Behavior

The camera should have a proper name.

### Environment

Ubuntu 20.04, lcdr unpacked client.

**Comment by NealSpellman** [comment] 2021-12-11 16:40
Same as #112; this camera is not a Live item, so it doesn't have a name. If you'd like to give it one, you can add an entry into Locale. Closing this for now since it is not a bug.

**Closed by NealSpellman** 2021-12-11 16:40 UTC
Labels: bug, triage
